### PR TITLE
Upgrade to React Native v0.50 + Flow v0.56

### PR DESCRIPTION
**Pull request by hawkrives**
It begins! This is an alternative to #1888; I'm marking the commit ranges in this PR so you can view them, instead of having separate PRs.

You can review either set, I guess.

---

Closes #1840.
Introduces merge conflicts with probably every open PR.
Alternative to #1888.

---

Just to start off, this might get a bit messy.

We're going to have a merge sequence.

1. `component-changes` ⩵ [`1f21b23..e8b4d34`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/1f21b23..e8b4d34)
2. `dependency-updates` ⩵ [`9400a9f..6d96330`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/9400a9f..6d96330)
3. `flow-typed-updates` ⩵ [`0a36c05..8423b4f`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/0a36c05..8423b4f)
4. `full-rn-0.50` ⩵ [`dd31354..b68bd06`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/dd31354..b68bd06)

---

# ⓵ Upgrade to React Native v0.50
Diff: [`dd31354..b68bd06`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/dd31354..b68bd06)

This section is pretty much the result of running `react-native-git-upgrade 0.50.3` on our app. It's just the native / bundling changes that we needed.

Things of note: 

- There are no longer separate `index.android.js` and `index.ios.js` entry points; they are merged into `index.js`. This is effectively not a change for us, since we made them both one line long (import `source/root.js`).

- Flow has been upgraded from v0.45 to v0.56 🎉 

- I renamed the package in package.json

    We changed from AllAboutOlaf to all-about-olaf a while ago because npm was complaining about not liking upper-case names or something. However, because we originally set up the project as AllAboutOlaf, react-native-git-upgrade can't find the project to upgrade it unless I remember to reset this field. So I just changed it back.

- I told Greenkeeper to ignore the `react` package, since we can't update it without updating react-native

# ⓶ Update flow type definitions for Flow v0.56
Diff: [`0a36c05..8423b4f`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/0a36c05..8423b4f)

This section is what you get when you run `flow-typed update`.

… and I also wrote manual type definitions for some of the libraries.

- `react-native-alphabetlistview`
- `react-native-sortable-list`
- converted the typescript def for `css-select`
- `delay`
- `get-urls`
- `html-entities`
- `junk`
- had to turn off `minimist`'s because it conflicted with something deep inside the react-native cli
- kinda did something for `moment-timezone`
- wrote one for `pify` but then flow-typed dropped one in my lap so I used that instead
- `react-native-button`
- `react-native-calendar-events`
- `react-native-communications`
- updated my custom def for `react-native-linear-gradient`
- `react-native-restart`
- `react-native-safari-view`
- updated my custom def for `react-native-tableview-simple`
- `string-natural-compare`
- `titlecase`

# ⓷ Update dependencies that were blocked on a React-Native update
Diff: [`9400a9f..6d96330`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/9400a9f..6d96330)

This section is what you get when you, er, update a bunch of packages.

Not much else to say.

I apparently also cleaned up the .flowconfig a bit in here. Oh well.

Updated dependencies:

- react-navigation
- react-native-calendar-events
- react-native-network-info
- react-native-safari-view
- babel-preset-react-native
- react-test-renderer

# ⓸ Do the Flow v56 / React-Native update 💃
Diff: [`1f21b23..e8b4d34`](https://github.com/StoDevX/AAO-React-Native/pull/1892/files/1f21b23..e8b4d34)

This section is the remaining fixes needed to make the app run / typecheck again.

You can probably review this section one commit at a time, if you so wish.

Things to note: 

- `import React` → `import * as React`

    Imports the type definitions from React, as well as the JS exports. So, not strictly necessary, but if we get in the habit of writing it out we won't wonder why we can only sometimes do `React.Node`.

- A `NetInfo` event changed its name.

- f879e9c is the biggie – it's where I did the `… extends React.Component<DefaultProps, Props, State>` → `… extends React.Component<Props, State>` changeover.

- The remaining commits are fixing flow config problems, mocking `react-native-safari-view` in Jest, and fixing more flow problems.

I believe that there are still two known issues:

- [ ] There's a dark line at the bottom of our toolbar now
- [ ] "Error: the `<Image>` component cannot contain children. If you want to render content on top of the image, consider using absolute positioning." (https://github.com/facebook/react-native/commit/c55fae1e2697520a55d23a0816552bec09920142)

### CODE REVIEW

**Comment by hawkrives** [comment]
> We like to try and keep PRs under 400 lines, and this one was 8238 lines.

lol. Sorry @stodevx-bot.

**Comment by hawkrives** [comment]
Build failure is on iOS:

> ▸ Running script 'Bundle Data Files'
> ▸ Running script 'Bundle React Native code and images'
> ** ARCHIVE FAILED **
> The following build commands failed:
> PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/travis/Library/Developer/Xcode/DerivedData/AllAboutOlaf-axgziitukyyjlyfvuepevdfannhu/Build/Intermediates.noindex/ArchiveIntermediates/AllAboutOlaf/IntermediateBuildFilesPath/AllAboutOlaf.build/Release-iphoneos/AllAboutOlaf.build/Script-00DD1BFF1BD5951E006B06BC.sh
> (1 failure)

**Comment by hawkrives** [comment]
screen shot 2017-11-14 at 5 43 55 pm

Here's a screenshot of the dark border on the toolbar.

**Review by rye — APPROVED** [review]
I think the added border is fine and shouldn't necessarily be removed.  It's subtle enough that I doubt most users will care.  We have something similar in Android, anyhow.

I'll take my approval from the 4-stage PR chain and apply it here; this should be fine.

**Comment by hawkrives** [comment]
@rye I only list it because it’s a difference from what we used to have, which I carefully tuned to match what iOS does. The two todos I've noted aren’t necessarily merge blockers.

**Review by drewvolz — APPROVED** [review]
I’ve looked thru it but haven’t compiled it. Thanks for all the work, @hawkrives! I trust you on this one 👍

**Pull request merged**
