### PR TITLE
Course search enhancements

### LINKED ISSUE #2341: Search courses by short/long title, description
I think we’re only searching by short title right now. Use:

Algorithms and Data Structures reveals that “Algorithms/Data Struc” is searchable but the long title containing “Structures” is not

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #2341
* Fuzzy search
* Search titles

The titles are additional to the course names.
Does not solve searching for names where middle initials prevent a match in prof names

### CODE REVIEW

**Comment by hannesmcman** [comment]
Do we want to add search by description here? 
```javascript 
(course.description || []).some(description =>
	description.toLowerCase().includes(query)
)
```

**Comment by drewvolz** [comment]
Maybe. Thoughts, anyone else? @rye @hawkrives

**Comment by hawkrives** [comment]
I feel like searching description is going to generate false positives and be really slow. 

I'd like some benchmarks on search speed with and without description searching. 

Just log performance.now before and after the filter process happens.

**Comment by hawkrives** [comment]
With that said, I'd be fine with merging this PR as-is, and checking on description searching in a followup.

**Review by hawkrives — APPROVED** [review]

**Comment by drewvolz** [comment]
Are you alright with merging these changes, @hannesmcman?

**Review by hannesmcman — APPROVED** [review]

**Pull request merged**
