### PR TITLE
Upgrade to React Native v0.60.4

### PR DESCRIPTION
**Pull request by hawkrives**
This was honestly one of the nicest RN upgrades I've had so far.

- Enabled auto-linking for Android modules (iOS requires cocoapods, and seems to still work with the manual linking method, so… I'm going to just leave it alone.)
- I enable "gradle dependency locking". We'll see what it does for us.
- We're now using AndroidX. Google should be happy.
- I've switched to `react-native-location`, `react-native-webview`, and `react-native-community/netinfo` (closes #3854)
- I upgraded `react-native-gesture-handler` (closes #3946)
- I had to use an `any` in filter-popover, because Flow decided that a variable was unreadable.
- I switched SelectableText to a functional component
- I removed the unused `react-native-searchbar-controlled` dep from frogpond/searchbar
- I had to add `jetifier` as a postinstall step (via the RN changelog; part of AndroidX)
- I switched the patch application to use `ls | xargs patch` because `patch` seemed to be unhappy about applying two patches at once (it returned an error labelled 0002, with the contents of 0001, and didn't actually apply 0001)
- Switched the geolocation in wifi-tools to use react-native-location (tested myself last night on iOS; haven't test on Android)
- we saved ~200 lines in the Yarn lockfile!

---

One thing we can look into later is switching to that new Hermes JS engine on Android:

engine | bytes | mb
--- | --- | ---
jsc | 45905164B | 45M
hermes | 32664452B | 32M

However, it spat out a lot of errors like the following, so I would recommend letting it rest for a while.

> /Users/rives/Projects/aao/android/app/build/generated/assets/react/release/index.android.bundle:458:983: warning: the variable "ErrorUtils" was not declared in function "f 45#"

### CODE REVIEW

**Comment by drewvolz** [comment]
> Switched the geolocation in wifi-tools to use react-native-location (tested myself last night on iOS; haven't test on Android)

Let's test this before merging

**Comment by drewvolz** [comment]
Also, running from the CLI instead of Xcode returns messages about autolinking

```
yarn run ios
yarn run v1.17.3
$ react-native run-ios
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - @mapbox/react-native-mapbox-gl: https://npmjs.com/package/@mapbox/react-native-mapbox-gl
  - react-native-sentry: https://github.com/getsentry/react-native-sentry
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @hawkrives/react-native-alternate-icons (to unlink run: "react-native unlink @hawkrives/react-native-alternate-icons")
  - @mapbox/react-native-mapbox-gl (to unlink run: "react-native unlink @mapbox/react-native-mapbox-gl")
  - @react-native-community/netinfo (to unlink run: "react-native unlink @react-native-community/netinfo")
  - react-native-calendar-events (to unlink run: "react-native unlink react-native-calendar-events")
  - react-native-custom-tabs (to unlink run: "react-native unlink react-native-custom-tabs")
  - react-native-device-info (to unlink run: "react-native unlink react-native-device-info")
  - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
  - react-native-keychain (to unlink run: "react-native unlink react-native-keychain")
  - react-native-linear-gradient (to unlink run: "react-native unlink react-native-linear-gradient")
  - react-native-location (to unlink run: "react-native unlink react-native-location")
  - react-native-network-info (to unlink run: "react-native unlink react-native-network-info")
  - react-native-restart (to unlink run: "react-native unlink react-native-restart")
  - react-native-safari-view (to unlink run: "react-native unlink react-native-safari-view")
  - react-native-search-bar (to unlink run: "react-native unlink react-native-search-bar")
  - react-native-sentry (to unlink run: "react-native unlink react-native-sentry")
  - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
  - react-native-webview (to unlink run: "react-native unlink react-native-webview")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Found Xcode project "AllAboutOlaf.xcodeproj"
```

**Comment by drewvolz** [comment]
Orgs and dictionary hit this
image

---

We'll have to fixup our fork of [alphabet-listview](https://github.com/allaboutolaf/react-native-alphabetlistview) to stop using a deprecated import of `ListView` and instead use `SectionList`. We'll also have to renamed the imported component in that project that's already `SectionList` to be something else.

**Comment by drewvolz** [comment]
I'm also hitting infinite loading / spamming of the "invalid login" prompt.

1. Settings > bogus credentials > login
2. Home > stoPrint

**Comment by hawkrives** [comment]
@drewvolz Could you file a new issue for that? Or can you only reproduce on this branch?

**Comment by drewvolz** [comment]
Okay, so it is an existing issue. Good call.

**Review by drewvolz — APPROVED** [review]
🥇👍🎈🎉 thank you for all of the work, @hawkrives. I think we need to fixup our outside listview dependency which I'm okay with us doing in a separate PR.

**Comment by hawkrives** [comment]
Let's nightly it and fix things in followup PRs

**Pull request merged**
