### PR TITLE
WIP: Explore moving nightlies and tagged builds to Circle

### PR DESCRIPTION
**Pull request by hawkrives**
WIP WIP WIP

Ideas:

- Share a build context between two macOS / Linux VMs to share the built app, and use the first one to build and the second to deploy, allowing more workflow-level control?

### CODE REVIEW

**Comment by hawkrives** [comment]
Current status: auth works

Something in the iOS build isn't writing files to logs, so Danger's failing.

**Comment by hawkrives** [comment]
Turns out that I had only asked check_build to write, not build itself. 

Now I just need to clean up the config and make sure the rest of the logic transferred.

**Review by rye — COMMENTED** [review]
We will want to remove all the extra commented gobbledygook later, but this looks very good so far.

**Comment by hawkrives** [comment]
Closed in favor of #2172

**Pull request closed without merging**
