### PR TITLE
Webcams in webbrowsers

### PR DESCRIPTION
**Pull request by hawkrives**
I think it's an improvement over the status quo.

&nbsp; | iOS | Android
--- | --- | ---
Old | old ios | old android
New | new ios | new android

### CODE REVIEW

**Comment by drewvolz** [comment]
Closing and reopening due to #856 and #853 to re-trigger the build.

**Comment by drewvolz** [comment]
Main | Detail
---|---
 |

**Comment by drewvolz** [comment]
Android is a little special. We'll need to poke at the behavior a little more. It seems to require a tap on the play button then a tap on the full-screen icon. We'll figure this out. Chrome tabs...

**Comment by drewvolz** [comment]
Closing and reopening due to #857

**Comment by drewvolz** [comment]
This is an improvement over the original implementation. @hawkrives what are your feelings on Android's functionality with this PR?

**Comment by hawkrives** [comment]
I am now proposing as follows:

- On iOS, when you tap the button it will open SFViewController to the stream.
- On Android, the button opens to the webcam page, where you can attempt to play it.

Some devices / browsers will be able to play the stream on Android; some won't.

**Pull request merged**
