### PR TITLE
Remove Enzyme

### PR DESCRIPTION
**Pull request by hawkrives**
Enzyme (and react-native-mock) are causing our test failures.

https://github.com/airbnb/enzyme/issues/614#issuecomment-254139719 mentions that enzyme isn't quite intended for react-native testing (yet?), which I knew, but it was "mostly" working until last week.

This PR removes enzyme and related tools.

It also disables the two interaction tests I had written, since I haven't figured out how I want to approach interaction simulation without enzyme present yet.

### CODE REVIEW

**Comment by hawkrives** [comment]
So the current build failure... is that Travis isn't ending the JS build on a successful finish, for some reason.

**Comment by drewvolz** [comment]
https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out

**Comment by drewvolz** [comment]
So we might have some processes still running. 

@hawkrives suggested a way to debug this:
> 1. Make a new branch called `travis-stalls` or something
> 2. Disable the non-js builds on it (that's the first commit)
> 3. Then comment out the `after_success` section, wait for it to finish
> 4. Then comment out danger
> 5. Then comment out each part of the js' scripts section, waiting for each run to finish (none of the js scripts need any other of the scripts to have run)

**Review by drewvolz — APPROVED** [review]
:+1: :white_check_mark: :shipit: thanks for fixing the build!

**Comment by hawkrives** [comment]
I disabled the call to `ssh-add`.

I guess the ssh daemon was still running or something?

We don't use this key anymore; it used to be used for pushing changes back to github, but that's currently disabled.

**Pull request merged**
