### PR TITLE
Update credits styles

### PR DESCRIPTION
**Pull request by drewvolz**
* adds line break to credits paragraphs
* modifies position of contributors block

Before | After
---|---
before | after

### CODE REVIEW

**Review by elijahverdoorn — APPROVED** [review]

**Comment by hawkrives** [comment]
It looks like it also removed some of the padding under the "**Contributors**" and "**Acks**" headings?

**Comment by drewvolz** [comment]
I'm okay with that... objections?

**Comment by hawkrives** [comment]
I liked that padding, personally. I'm good with the reduction of space between sections, and the addition of the second paragraph, but I like having some space beneath the lower headings.

**Comment by drewvolz** [comment]
Alright. Changed back.

**Pull request merged**
