### PR TITLE
Add Report-a-problem to Building Hours

### PR DESCRIPTION
**Pull request by hawkrives**
This is actually 5 PRs:

- Split the building hours list out of the index file
- Make all break schedules use the "full" schedule format and remove normalizeBuildingHours
- Split building-hours-helpers into individual files
- Share some components into the /source/views/components folder
- Add a report-a-problem view to Building Hours

I … should probably split it apart.

### CODE REVIEW

**Comment by hawkrives** [comment]
Luckily I did those first three before I did anything else, so they'll split out easily.

**Comment by hawkrives** [comment]
I'll split it tomorrow.

**Review by drewvolz — APPROVED** [review]
Wow! Let’s hope this works 🤷‍♂️

**Comment by hawkrives** [comment]
3 of the 5 of these partial PRs can be merged into `master`, I think, instead of `react-navigation-take-2`.

**Comment by hawkrives** [comment]
Closed in favor of #1171.

And #1166, #1167, #1168, #1169, and #1170.

**Pull request closed without merging**
