### PR TITLE
Add safety view

### LINKED ISSUE #3335: Add Safety Committee tile
The original request: (important bits bolded)

>Along with that, IT has helped us create **a vanity URL** which will direct everyone to **a Google form** to report unsafe winter walking conditions.
>
>One item we'd love to incorporate with these posters is the ability for students (and maybe some faculty and staff too) to access the Google form via the [All About Olaf] app. **Is there any way another "tile" could be created for "Report a Safety Concern" that could link to the following page? [link]**

See the email for the link.

This feature was requested for delivery by January 18th. Our 2.7.0 milestone says 2019-01-01.

---

- @hawkrives says he wants to maybe make the "Help" menu on the bottom, and that may be a place for this to go to. For now, @rye thinks it goes into Home screen, or gets a card in Help.
- Since the big part of the flow is a Google Form, we should consider kicking people out to their default browser. @rye's google-fu says [`react-native`'s Linking is a good idea?](https://facebook.github.io/react-native/docs/linking.html)
  - E.g. `Linking.openURL(url).catch(err => console.error('An error occurred', err));`?

---

As always, feel free to self-assign and take it on.

### PR DESCRIPTION
**Pull request by hannesmcman**
Resolves #3335.

We need a new gradient @hawkrives. Can you add one?

### CODE REVIEW

**Review by rye — DISMISSED** [review]
Needs a CHANGELOG update

**Review by drewvolz — COMMENTED** [review]
Thanks @hannesmcman for picking up this task! It works really well 👍

**Review by drewvolz — DISMISSED** [review]
I think we need a new gradient? `c.tealToSeafoam` is a dup of stoPrint's gradient.

**Comment by drewvolz** [comment]
> We need a new gradient @hawkrives. Can you add one?

(sorry, just noticed your comment in the original PR @hannesmcman)

**Comment by drewvolz** [comment]
I took a stab at a gradient

image

**Review by drewvolz — APPROVED** [review]
👍 :shipit:

**Comment by hawkrives** [comment]
That should have black text, not white.

**Comment by drewvolz** [comment]
I checked with the accessibility link we use. Looks like you are right -- my colors are not accessible.

**Comment by hawkrives** [comment]
Please update and merge a PR switching to black text? Tonight if possible. 

I'm on low internet so I can't do anything.

**Pull request merged**
