### PR TITLE
github action to update lint and tsc files

### PR DESCRIPTION
**Pull request by drewvolz**
Allow for updating the eslint problems and ts counts/errors files through pull request comments.

---

This may not be working or doing what it says it should do yet.

### CODE REVIEW

**Comment by drewvolz** [comment]
update tsc and lint files

**Comment by hawkrives** [comment]
for what it's worth, my attempt at auto updating doesn't even run anymore lmao - it never triggers for some reason

**Comment by hawkrives** [comment]
but, I also wouldn't be opposed (whichever is easier) to having GitHub automatically push updated eslint/tsc files if they change, even without the magic comment

**Comment by drewvolz** [comment]
I think this may only end up working if this were to be merged into `master`. Based upon @hawkrives comment I don't know if it will work as it should, though.

**Comment by drewvolz** [comment]
I'm willing to back this change out if it doesn't work, but should we see if this works by merging it?

Alternatively, clone the repo and give it a try?

**Review by hawkrives — APPROVED** [review]

**Comment by drewvolz** [comment]
@rye any thoughts? I know this is possibly broken at the moment so I can just as easily close this out.

**Review by rye — APPROVED** [review]

**Pull request merged**
