### PR TITLE
Start a changelog

### PR DESCRIPTION
**Pull request by drewvolz**
Starts implementing #2964.

* Creates the initial changelog file
* Marks entries for v2.6.0 - v2.6.3

### CODE REVIEW

**Review by rye — COMMENTED** [review]
While I like this, I think the general style we're looking at is more technical with this.

My idea currently is that each branch that gets merged into `master` should get its own 1..n ChangeLog entries. Assuming that PR's are atomic, (as they rightfully should be) this should be a no-brainer.

This means that the Release Notes (not the ChangeLog) will be a much-condensed and cherry-picked version of the ChangeLog for that version. But I think that's the easiest way to do this.

@drewvolz, would you want to take another pass at this? If not, I can work on some changes to this PR to make it more in line with the style I think we're after.

**Comment by drewvolz** [comment]
@rye how about my second pass?

**Review by rye — DISMISSED** [review]
Much better.

My only other possible gripe or suggestion is that we should keep things roughly in DAG order—that is, keep them relatively the same as when they entered `master`. Obviously, if two PR's are going in at roughly the same time, it may be hit or miss, but this would be a good target to hit.

This is an excellent starting point, though. Thanks for picking up the chore work.

**Review by hawkrives — DISMISSED** [review]
This looks pretty good to me!

@rye, I think that as we're adding changes, we will want to investigate the two methods for avoiding append-only conflicts in this gitlab blog post – https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

**Comment by rye** [comment]
@hawkrives and @drewvolz, I have added `merge=union` in `.gitattributes` to match files called `CHANGELOG.md`. See extended discussion in b336bb68164769a7dc519c0feac876daa97d587c or your inboxes for the patch.

**Review by rye — APPROVED** [review]
My approval is much stronger now.

**Comment by rye** [comment]
Since we've two (ish) approvers, is this good to go?

**Pull request merged**
