### PR TITLE
Fastlane fixes

### PR DESCRIPTION
**Pull request by rye**
**I am submitting this from a fork to test CI permissions on forked contributions.**

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
I'm not entirely sure … oh. I know why the checks didn't run. 

We run them on "push" events to _this_ repo. Dependabot pushes to this repo, but can't access the keys repo, so it fails. This PR is a push to another repo, so it's not running any events. 

I'm happy to merge this! It looks correct. 

We may need to investigate our GitHub actions settings, though…

**Review by drewvolz — APPROVED** [review]
Thanks, @rye!

**Comment by hawkrives** [comment]
We'll just need someone to use their admin privs - I'm probably afk tonight

**Comment by hawkrives** [comment]
To merge

**Pull request merged**
