### PR TITLE
Remove react-native-video from package

### PR DESCRIPTION
**Pull request by drewvolz**
As a follow-up to #1623, this PR removes all references to `react-native-video`.

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
We need to unlink it from the iOS and Android projects, as well.

**Comment by hawkrives** [comment]
I just removed the rest of rn-video from our project

**Comment by drewvolz** [comment]
Huh — so running `rn unlink react-native-video` did not work as I had thought. Maybe because we were using my fork?

**Comment by hawkrives** [comment]
Note: There's an ongoing Travis-on-macOS issue today (https://www.traviscistatus.com/incidents/h6gwvyq9zky0), as well as a really large queue that didn't clear out overnight. I would expect this PR to finally build sometime this evening, if all goes well.

**Comment by hawkrives** [comment]
@drewvolz – `rn unlink` doesn't seem to ever want to remove our Android packages. It just said "… is not installed" for me. It did do the iOS one, though.

**Comment by drewvolz** [comment]
I’ve had success with it in the past, I think? Oh well.

**Comment by drewvolz** [comment]
Thanks for fixing the Android build, @hawkrives. That has passed now.

**Pull request merged**
