### PR TITLE
Directory

### PR DESCRIPTION
**Pull request by elijahverdoorn**
Add a webview for the directory. Stolaf.edu already has a mobile view (although it's a bit wonky), so let's just use that until we can come up with something better.

### CODE REVIEW

**Comment by hawkrives** [comment]
@drewvolz and I found an xml endpoint for stalkernet and convinced Dan Beach to leave it expressly for use on-campus.

**Comment by hawkrives** [comment]
… which is part of what `/lib/stalkernet.js` does.

**Comment by drewvolz** [comment]
Making use of that endpoint that @hawkrives mentioned is ideal. We want to aim to be as native as possible in react-native! Shouldn't be more than a simple HTTP request to that endpoint

**Comment by elijahverdoorn** [comment]
I understand the purpose of react native and would agree that there it's better to do implement this as you described.
**Two problems:**
- Stalkernet added the need to login to perform a search. This is in accordance with FERPA law. The existing helper file does not deal with this, and even if the endpoint allowed it I would not publish something that was potentially invading student privacy.
- I am running out of time. Version 1 of the app needs to be ready by the end of August. I am currently thinking of version 1 as a Minimum Viable Product, so since the current implementation is functional I am going to focus on other areas.

Addressing this section will be high on the list of improvements for v2.

**Comment by hawkrives** [comment]
Wait - even on campus you have to log in?

Historically, on-campus has bypassed the login requirement.

**Edit:** Testing with the VPN shows that on-campus still bypasses the login requirement. This API that we found is only available on-campus. I'd been envisioning that the entire Stalkernet section would block you out when it didn't detect a 130.71 IP on the device, but even if it didn't the API wouldn't return anything if you were off-campus.

**Comment by hawkrives** [comment]
Also, what would you most like help with? I'd be happy to pitch in.

**Comment by elijahverdoorn** [comment]
@hawkrives From my VPN, yes. I support that change too, it was rather uncomfortable to me to allow anyone to access that data who was on the network, as I know that there are external people given that access.

I'll make a few more changes to the readme with things that you could do. Thanks for the offer!

**Comment by hawkrives** [comment]
Huh. I just logged in with my Olaf VPN and searched for you and didn't have to log in.

Hmm. I agree that it's a bit uncomfortable… perhaps we should communicate with Dan to check on expectations.

Maybe it's time to move the SIS login up to the app-level. We (read: @drewvolz) never really had a reason to before, since nothing else needed login.

Thanks for writing out a list of stuff!

**Comment by elijahverdoorn** [comment]
Accidental close :(

Yeah, App-level login would be good. I want it usable for anyone that doesn't have an Olaf login, so we would have to keep that in mind during implementation.

**Comment by hawkrives** [comment]
Yeah. How about - and this is spitballing off the top of my head - login is managed in "settings" (which we'd need to add), and we prompt for it whenever you try to open a section that needs login?

So, you open the app, and it works just fine. 

The first time you open SiS or Stalkernet, it pops up a interstitial modal for login, then stores that – somewhere, in persistent storage. You can log out by going to settings.

(If we wanted to be really fancy, we could add an lock icon or something to the auth-required buttons so you know before you tap.)

**Comment by elijahverdoorn** [comment]
Right, that sounds good. I don't know how the XML endpoint for stalkernet handles the login... If it returns the data without login we cannot use it until it gets fixed, that would open sensitive data to the public. I'll speak with Dan.

**Comment by hawkrives** [comment]
IIRC, it just doesn't exist unless you've got a 130.71 IP (aka on-campus/vpn). If it exists, it doesn't authenticate. LMK if that's incorrect.

**Comment by elijahverdoorn** [comment]
@hawkrives That's what I'm getting. I think that it would be best if it worked off-campus (for those with a login, of course). If the endpoint doesn't exist. maybe the webview is the best option? It's not pretty, but it seems to provide the most functionality. Do you have other ideas?

**Comment by elijahverdoorn** [comment]
Also updated the readme, feel free to take on any of the tasks that are listed in the TODO marked _PRs Welcome_.

**Comment by hawkrives** [comment]
… To be honest, I really just don't like the web interface for Stalkernet, so that's coloring my opinion on this quite heavily.

So. With that qualifier, I think it's quite reasonable to restrict Stalkernet use to the campus network only. If it's important that it be available to anyone with a login, anywhere, well… I suppose we could either tell them to go use the web browser, or just (since webviews are easy in RN) add a button to fall back to the web view?

**Comment by elijahverdoorn** [comment]
@hawkrives Fair enough, that sounds reasonable. I'll see if I can reconfigure my VPN to get passwordless access, then build this out a bit.

**Comment by hawkrives** [comment]
SInce I'm the one pushing for it, if you want to say "you want it, you build it" that's fair too 😜

**Comment by elijahverdoorn** [comment]
@hawkrives I'm already on it, I'll do it... You do streaming media.

**Comment by hawkrives** [comment]
Lol k

**Comment by drewvolz** [comment]
Would it be fair to ask that the directory URL end up in some sort of resources JSON file? Things break all too often when we can't control who makes changes and how often. If they suddenly change the directory address, it will break, so quick editing on the app's part might be handy. This is the design principle I am hoping to aim for in the SIS portion as well (which I have not started on) -- where the URLs are extracted into a resource JSON file. I have been burned by this before!

I would be willing to create the separate resources JSON file and add that URL to it. Just let me know.

**Comment by elijahverdoorn** [comment]
@drewvolz I think that a URLs.json would be a good idea. Go for it!

**Pull request merged**
