### PR TITLE
Fix things

### PR DESCRIPTION
**Pull request by hawkrives**
This PR should:
- fix bugs in the courses screen
- fix bugs in the financials screen
- log the user out more consistently when the token expires
- tweak the visual design on the menu pages
- add "No News" and "No Events" to the news / calendar pages at appropriate times

### CODE REVIEW

**Comment by drewvolz** [comment]
I am able to check items 4 and 5 of this list, but someone with an active St. Olaf account (@elijahverdoorn @ekmanzu @zimmer18) will have to confirm items 1-3.

**Comment by elijahverdoorn** [comment]
I said I'd get to this tonight, but it'll have to wait until tomorrow, sorry - math is hard.

**Comment by drewvolz** [comment]
> - tweak the visual design on the menu pages
> - add "No News" and "No Events" to the news / calendar pages at appropriate times

Items 4 and 5 look good -- compiled them and looked at the code last night.

**Comment by hawkrives** [comment]
I pushed some more changes. 
- I removed the animated react-native-collapsible component
- I fixed up the menu views
- I tweaked line width and color in the table views (Transportation, Calendar, and News)

**Comment by hawkrives** [comment]
I vote that we merge #296 first, then I can fix this up to coexist with his changes.

**Comment by elijahverdoorn** [comment]
Confirming that this works and looks good. I think there are still some bugs in the financials screen that are causing it not to show the meals, but this change is a step forward.

EDIT: After looking at the code for the meals, it's clear that we don't even try to put that info in place. My bad.

**Review by elijahverdoorn — APPROVED** [review]
Looks good.

**Comment by hawkrives** [comment]
Yeah, the stuff was hidden when Drew and I last looked for it. I'll open an issue where we can discuss it. (#303)

**Comment by hawkrives** [comment]
I need to edit this to make all the menus have a consistent design, then it'll be ready.

**Comment by hawkrives** [comment]
Closes #304

**Comment by hawkrives** [comment]
:shipit:

**Pull request merged**
