### PR TITLE
Add express bus data

### LINKED ISSUE #199: Add Express bus routes
The bus times that are currently shown do not account for the express bus, which runs to a limited number of stops. We should find a way to display the express bus data, either in another tab or just another list on the bus tab of the transportation section.

### PR DESCRIPTION
**Pull request by hawkrives**
Closes #199.

This restructures the bus views and bus schedule data, and adds Express data.

I used the attached image as my source for the express data.

img_4633

This lays the groundwork for future improvements to the bus views.

The time format has changed from "HH:mm:ss" to "h:mma" (eg. 17:34:00 to 5:34pm).

I had to add the ability specify days for certain schedules for the express route.

### CODE REVIEW

**Comment by hawkrives** [comment]
Scratch that. I came up with another data reformatting, I think. I was trying to use the existing one for implementing a progress view, but I'm having a hard time doing it when the routes are so twisty*.

*twisty isn't what I mean. I'll revisit this comment when my mind is clearer.

**Comment by hawkrives** [comment]
image

**Comment by drewvolz** [comment]
Closes #199

You said it up above in the description, but I'm not so sure it closed it. Let's try again.

**Comment by hawkrives** [comment]
… we haven't merged this PR yet.

**Pull request closed without merging**
