### PR TITLE
🖼 Implement Android's "Adaptive Icons"

### LINKED ISSUE #889: Support Android O's "Adaptive Icon" feature
Docs: https://developer.android.com/preview/features/adaptive-icons.html.

> Android O introduces adaptive launcher icons, which can display a variety of shapes across different device models. For example, a launcher icon can display using a circular shape on one OEM device, and display a squircle on another device. Each device OEM provides a mask, which the system then uses to render all icons with the same shape. The new launcher icons are also used in shortcuts, the Settings app, sharing dialogs, and the overview screen.

&nbsp; | &nbsp;
--- | ---
 | 

See the [Creating Adaptive Icons](https://developer.android.com/preview/features/adaptive-icons.html#Creating) section for more information on making them.

---

My take: this looks even simpler than the current icon.

We provide the glyph and a background, then let the system render them into one bitmap.

### PR DESCRIPTION
**Pull request by rye**
Closes #889.

In short, this PR

- Adds a new mipmap definition for the launcher which will be used on API 26+ devices
- Adds two new vector drawables which are composited into a dynamic "[adaptive icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)"

These were originally converted using [an online tool](https://svg2vector.com/) (soft paywall) from slices of the "AAO Logo" Sketch project.

# Known issues
- [x] The icon is a bit "zoomed-in" (need to review guidelines and see if and where scaling should be applied)
- [x] ~XML files need to be reformatted with tabs appropriately used instead of spaces everywhere~ (no need)
- [x] Documentation should be prepared for how to update these. (see: https://github.com/StoDevX/AAO-React-Native/wiki/Icon-Design)

# Questions raised
- Do we want to create a `roundIcon` variant?
- Should we constrain the API level to 26+ at some point? What is our timeline for so doing?

# Screenshots

"Device Default" | "Square" | "Teardrop"
---|---|---
Screenshot_1569769832 | Screenshot_1569769822 | Screenshot_1569769808
**"Squircle"** | **"Rounded Rectangle"** | …
Screenshot_1569769796 | Screenshot_1569769773

### CODE REVIEW

**Comment by rye** [comment]
# Updated screenshots

"Device Default" | "Square" | "Teardrop"
---|---|---
Screenshot_1569771676 | Screenshot_1569771692 | Screenshot_1569771703
**"Squircle"** | **"Rounded Rectangle"** | …
Screenshot_1569771713 | Screenshot_1569771728 |

**Comment by rye** [comment]
# Updated screenshots

"Device Default" | "Square" | "Teardrop"
---|---|---
Screenshot_1569778545 | Screenshot_1569778534 | Screenshot_1569778519
**"Squircle"** | **"Rounded Rectangle"** | …
Screenshot_1569778510 | Screenshot_1569778499 |

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
I don’t think we need a round icon; IIRC, that really only applies to Marshmellow? 

API v26 as a minimum: I’d say when we have … um. <10% of semester’s active users on <26?

**Comment by rye** [comment]
Alright, sounds good. We can just keep our `minSdkVersion` where it is right now; our `-*dpi` dirs _should_ allow those variants to keep working as long as we need them to.

**Review by drewvolz — APPROVED** [review]
👍 :shipit:

**Pull request merged**
