### PR TITLE
There, and (hopefully) Not Back Again: From RN 0.61 to RN 0.66

### PR DESCRIPTION
**Pull request by hawkrives**
Closes #5512, #5499, #5498, #5497, #5480, #5089, #5067, and #5394

packages to upgrade:

- [x] `react-native-calendar-events` @ 2.2.0 – @hawkrives "Probably done. Breaking change was requiring RN 0.60+."
- [x] `react-native-device-info` @ 8.4.3 – @hawkrives "Probably done. Breaking changes were requiring iOS 10 and then Xcode 12."
- [x] `react-native-paper` @ 4.9.2 – @hawkrives "Done? v3: [guide](https://github.com/callstack/react-native-paper/wiki/Migration-guide-for-3.0) - minimal changes. v4: [guide](https://github.com/callstack/react-native-paper/wiki/Migration-guide-for-4.0) - minimal changes."
- [x] `react-native-popover-view` @ 4.1.0 - @hawkrives "Probably done. I think the breaking change was a new RN minimum version."
- [x] `react-native-reanimated` @ 2.2.3
   - @hawkrives "I don't even think we use this. Removed, unless something breaks."
   - @drewvolz "Introduced as a dep of react-navigation  –– unclear if Android still needs it"
- [x] `react-native-restart` @ 0.0.22 – @hawkrives "I think it's done. I don't think there were any breaking changes."
- [x] `react-native-screens` @ 3.9.0 – @hawkrives "Done. Removed call to `enableScreens()`."
- [x] `react-native-tableview-simple` @ 4.3.0 – @hawkrives "I think it's good. Breaking change was requiring a new version of RN."
- [x] `react-native-vector-icons` @ 9.0.0 – @hawkrives  "Done. v7: drop `Icon.AndroidToolbar`. v8: drop `Icon.TabBarItemIOS`. v9: changes to rn-web/rn-desktop."
- [x] `react-native-webview` @ 11.14.2 – @hawkrives "Done. v9: ok. v10: defensive coding of gradle. v11: security fix; links that open in new tabs/windows (such as `<a target="_blank">`) will now prompt to open in the system browser, rather than re-using the current WebView."
- [ ] `@react-navigation/native` @ 6.0.6

---

Builds/Runs:
- [ ] Android
- [x] iOS

React Navigation status:
- [x] Home
- [ ] Settings
  - [ ] Types 
  - [x]  FAQs
- [x] Calendar
  - [x] List
  - [x] Detail
  - [x] Add to calendar
- [ ] Hours
  - [ ] Types 
  - [x] List
  - [x] Detail
  - [x] Editor
  - [x] Reporter
- [ ] Contacts
  - [ ] Types 
  - [x] List
  - [x] Detail

### CODE REVIEW

**Comment by hawkrives** [comment]
For react-navigation:

- https://reactnavigation.org/docs/upgrading-from-5.x
- https://reactnavigation.org/docs/typescript/
- https://reactnavigation.org/docs/native-stack-navigator
- https://reactnavigation.org/docs/5.x/upgrading-from-4.x
- https://reactnavigation.org/docs/material-bottom-tab-navigator/

I have ported (maybe) the root navigator and the calendar view.

Types are v. nice.

I haven't run it yet; probably doesn't run.

I barely touched the entrypoint.

**Comment by drewvolz** [comment]
The iOS project should be in a state where it builds and runs. Android as of yet will not compile for me.

I pushed changes to be able to get the homescreen, top-level settings button, and the settings screen to load. I also made a few tweaks: moved the settings button to the right side and configured the settings view to show in a dismissible modal.

There are other changes to handle deprecations/renamings as well. Also had to downgrade Flipper-DoubleConversion, add a babel plugin, and remove some of our es6 polyfills.

**Comment by drewvolz** [comment]
Updated the initial PR description with a list of what is being worked on. 

Noticing a nice pattern that Hawken added in event-detail and calendar –– exporting Navigationkey, NavigationParams and consuming them in navigation's types and routes. I plan to refactor Settings and Hours to adhere to that pattern.

Pushed a first pass at hooking up building hours list, detail, editor, and reporter. There's more work needed to adhere to the standard.

**Review by drewvolz — APPROVED** [review]
Let's merge this and continue to work on Navigation and friends in smaller chunks.

**Pull request merged**
