### PR TITLE
Update sis and news faqs

### PR DESCRIPTION
**Pull request by drewvolz**
* Explanation on long update delay
* Status update on SIS
* Status update on News

### CODE REVIEW

**Comment by hawkrives** [comment]
Make them h1s instead of h2s, please?

The embedded stylesheet has a rule for h1s.

**Review by hawkrives — CHANGES_REQUESTED** [review]
Make them h1s instead of h2s, please?

The embedded stylesheet has a rule for h1s.

**Review by hawkrives — APPROVED** [review]
We chatted about this out-of-band.

> @drewvolz: I think the question text is very large. When do you honestly see text that large in mobile apps? When you’re reading something, especially.
> @hawkrives: So make it smaller

And so he did.

**Comment by drewvolz** [comment]
Now that News is fixed, we need a PR to rid of the news FAQ.

**Pull request merged**
