### PR TITLE
Update to Xcode 10.1

### LINKED ISSUE #3290: iOS builds need to switch target SDK versions
> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "All About Olaf". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> - SDK Version Issue - This app was built with the iOS 11.4 SDK. 
>
>   Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.
>
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

### PR DESCRIPTION
**Pull request by hawkrives**
Closes #3290

### CODE REVIEW

**Comment by hawkrives** [comment]
oh wait, the build did pass – detox's build failed!

image

**Comment by hawkrives** [comment]
wait, it passed?

**Comment by hawkrives** [comment]
hokay… imo that shouldn't have fixed the build, but it did. so.

now putting PR up for review.

**Review by rye — APPROVED** [review]
Looks good!

**Pull request merged**
