### PR TITLE
Olecard json endpoint

### PR DESCRIPTION
**Pull request by hawkrives**
Supersedes https://github.com/StoDevX/AAO-React-Native/pull/1794
Closes https://github.com/StoDevX/AAO-React-Native/issues/1792

I … haven't actually tested this; I need to do some actual work now.

But I think all the logic is good now.

### CODE REVIEW

**Review by rye — COMMENTED** [review]
| Logged out | Logged in |
|---|---|
| screen shot 2017-10-18 at 11 38 53 am | screen shot 2017-10-18 at 11 37 58 am |

Is there any way we can change `17 meals/week-$130 Flex$'s/semester` to something more pleasant?

**Comment by rye** [comment]
I realize that they come this way from the API, but I think we might be able to do parsing to make it better.

**Comment by hawkrives** [comment]
I'd like to do that parsing server-side, I think?

**Comment by hawkrives** [comment]
I'll find a list of the options and clean them up in the responses there

**Comment by rye** [comment]
Doing that server-side would be very helpful.

**Review by rye — APPROVED** [review]

**Pull request merged**
