### PR TITLE
Oleville view

### PR DESCRIPTION
**Pull request by elijahverdoorn**
This adds the Oleville view, which for now just pulls from the oleville API, getting the latest posts and displaying them, similar to the news but with a focus on images.

### CODE REVIEW

**Comment by elijahverdoorn** [comment]
Merge conflicts resolved.

**Comment by elijahverdoorn** [comment]
this closes (for v1, anyway) issue #14

**Comment by hawkrives** [comment]
LGTM

**Comment by hawkrives** [comment]
(this is probably a case where I should have done a normal merge commit, rather than squash + merge. oh well.)

**Pull request merged**
