### PR TITLE
[WIP] Re-enable nightly change detection

### PR DESCRIPTION
**Pull request by hawkrives**
Reverts and fixes #3288 

For merge after a successful nightly.

### CODE REVIEW

**Comment by hawkrives** [comment]
circle says:

```
fatal: --unshallow on a complete repository does not make sense
```

/cc @rye

**Comment by rye** [comment]
That error makes sense.

Is it not possible that our `git log` is doing something messy?

I'd prefer to avoid using `--since="26 hours ago"` since it's ambiguous.  Why don't we try doing something like `$(date -Iseconds --date="26 hours ago")` and shoving that into the `--since` flag?

**Comment by hawkrives** [comment]
I mean, I'm fine with that, but I think that supporting natural language parsing is a well-established part of `git log`.

Anyway. I'll update this PR to do that, instead, and we can try it tonight.

**Comment by rye** [comment]
That's probably not gonna work. We should instead use `Time` (core) and/or `DateTime` (stdlib)

**Comment by hawkrives** [comment]
oh, that's true. it does want an absolute date.

**Comment by rye** [comment]
Oh and we could shovel `2>&1` and if `^warning` matches we could throw and diagnose that way

**Comment by hawkrives** [comment]
i like that too

**Comment by hawkrives** [comment]
but um. the `sh` function should be dumping the output of the command to stdout?

**Comment by hawkrives** [comment]
also I just realized that this block

```
git checkout master
git reset --hard origin/master
git checkout "$CIRCLE_BRANCH"
git reset --hard "origin/$CIRCLE_BRANCH"
```

will result in un-reproducible builds. Can we make it set the tip of CIRCLE_BRANCH to the given commit sha?

**Comment by hawkrives** [comment]
or something?

**Comment by rye** [comment]
> but um. the sh function should be dumping the output of the command to stdout?

Yes, but `sh` doesn't capture stdout, I think.

> also I just realized that this block
> 
> ```
> git checkout master
> git reset --hard origin/master
> git checkout "$CIRCLE_BRANCH"
> git reset --hard "origin/$CIRCLE_BRANCH"
> ```
> will result in un-reproducible builds. Can we make it set the tip of CIRCLE_BRANCH to the given commit sha?

Sure, but that's out of the scope of this PR.

We could drop the `git reset --hard "origin/$CIRCLE_BRANCH"` and instead `git reset --hard $CIRCLE_SHA1`. I _think_ that'll rewind properly.

We should _definitely_ be keeping `master` in sync with origin, that's the whole point of doing that block in the first place, and besides doing some weird reflog-fu which would likely break whenever Circle updates their checkout script, I'm pretty sure this is all we have.

That's why I wanted a custom checkout script in the first place. Then we have control.

**Comment by hawkrives** [comment]
```ruby
output = `#{cmd}`.chomp
puts output
```

Shouldn't that capture stdout?

**Comment by hawkrives** [comment]
And I agree with the out of scope thing. I'll file an issue for that.

**Comment by rye** [comment]
Towards this actual issue, I'll note the following:

It's entirely possible that Git is actually doing the right thing and saying `git log --after='26 hours ago'` is empty. Note how if you change `26 hours` with `2 seconds`, you'll likely get an exit 0 and no output. This means we might actually just have issues with timestamps and relative time. I think that's a much more likely thing to troubleshoot.

A great idea would be to `git show --format="%aI" --quiet HEAD` which would grab the commit date in ISO8601 form which can definitely be parsed.  We then pass that as our `--after=`, which would guarantee that we have our commits be correct.

Let's… merge this PR, so we get our "broken" code back. I can play around with this some more tonight.

- - -

Yes, @hawkrives, your code example does capture stdout.

But I'm concerned that git is writing to stderr, and it's just getting eaten somewhere or we're not seeing it.

Note that

```ruby
`>&2 echo "I'm an error"`.chomp
# => ""
```

That is to say, stderr completely bypasses the capture. So if git does as I hope—what it's supposed to—and prints its errors on stderr, it doesn't get caught by our script, and it's entirely possible that that gets lost.

Compare that with:

```ruby
`{ >&2 echo "I'm an error"; } 2>&1`.chomp
# => "I'm an error"
```

(Braces added to force the output redirection to take place on both ends)

So that's why we'd need redirection, to force stderr back into stdout for our consumption, if we want it.

Some defense of Ruby's logic here:

- The double-` style is likely intended for hacky settings where you don't care about stderr, or if stderr is emitted you probably don't want it mixed in with your stdout.
- There are better alternatives which keep both streams separate (e.g. `Open3.popen3`) and let you consume them as pipes rather than getting one giant string. They also let you inspect the exit status, which the double-` doesn't.

**Comment by hawkrives** [comment]
@rye I completely agree with ruby's default of only capturing stdout; I got confused from your comment,

> image

and failed to think straight.

---

Regarding merging this PR… okay, if we do a beta tomorrow. I want to make sure the login fixes actually work 🤞

**Comment by rye** [comment]
Sounds good to me. I may have a fix for the skipping logic before then.

**Review by rye — APPROVED** [review]
This final CL looks good. (Essentially just `git revert` lol)

**Pull request merged**
