### PR TITLE
Fixed NSAppTransportSecurity exceptions for BonApp

### PR DESCRIPTION
**Pull request by drewvolz**
- Fixed the non-secure urls that cafebonappetit uses
- Added the non-https url to the menu so that it loads

### CODE REVIEW

**Comment by hawkrives** [comment]
Whitespace bad. Fix whitespace, then good. Things moved randomly.

See without whitespace: https://github.com/StoDevX/AAO-React-Native/pull/63/files?w=1

**Comment by hawkrives** [comment]
Drew convinced me to fix his whitespace.

**Comment by hawkrives** [comment]
screen shot 2016-08-16 at 10 24 42 pm

It loads again.

**Comment by hawkrives** [comment]
Waiting for builds.

**Comment by drewvolz** [comment]
Good to go, @elijahverdoorn?

**Comment by elijahverdoorn** [comment]
Good work @drewvolz. Approved.

**Pull request merged**
