### PR TITLE
Release version 2.8.0, beta 2

### PR DESCRIPTION
**Pull request by hawkrives**
View [the comparison from v2.7.0](https://github.com/StoDevX/AAO-React-Native/compare/v2.7.0...v2.8.0-beta.2).

## Checklist
- [x] Branch pushed
- [x] Tag pushed
- [x] [GitHub release][release] created to target pushed tag
- [x] Release PR [successfully builds][c-branch] against `master`
- [ ] Signed-off/approved
- [x] GitHub Wiki [release notes updated][wiki]
- [ ] [Tag build passes][c-tag]
  - [x] Android deployed.
  - [x] iOS deployed.
- [ ] Release PR merged to `master`.

[release]: https://github.com/StoDevX/AAO-React-Native/releases/tag/v2.8.0-beta.2
[pr]: https://github.com/StoDevX/AAO-React-Native/pull/3572
[wiki]: https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes#v280
[c-branch]: https://circleci.com/workflow-run/1b1fd52c-c75b-4f87-b5cd-83948bad8e3b
[c-tag]: https://circleci.com/workflow-run/adc89649-551f-4bbc-8b15-1515033dccca

### CODE REVIEW

**Comment by hawkrives** [comment]
… apparently the iOS build failed and is running again

**Comment by hawkrives** [comment]
I would like to merge this, in order to start incrementing the version on master. And so we don't wind up with more tags that point at commits which aren't on master. 

Thoughts?

**Comment by rye** [comment]
That's the SOP, but iOS is still red for some reason.

**Comment by hawkrives** [comment]
iOS passed; Android passed, but failed to upload sourcemaps.

I would really like to merge this anyway, with no more build attempts. The code works; it's just the build process that's being wonky here.

**Review by rye — APPROVED** [review]
Fine

**Pull request merged**
