### PR TITLE
Use functional setState and don't call refresh in orgs

### PR DESCRIPTION
**Pull request by hawkrives**
We want to call fetchData because it 
* (a) doesn't incur a 500ms delay penalty on first load, and

### CODE REVIEW

**Comment by drewvolz** [comment]
Is (b) relevant? I don't think I've seen anything other than the `LoadingView` here. I think you're referring to the refreshable spinner at the top of the list... which may not be enabled here.

**Comment by hawkrives** [comment]
It is enabled here. I can't say _why_ you haven't seen it, but what I listed are the two things that calling getData instead of refresh will do.

**Comment by drewvolz** [comment]
StudentOrgs has a refreshing spinner? This is `StyledAlphabetListView` we're talking about.

**Comment by hawkrives** [comment]
It appears to not have a refresh indicator. Or do pull on refresh.

**Comment by drewvolz** [comment]
Now. I would _like_ for that to be there. Pull-to-refresh. That will have to wait until a custom `AlphabetList` component is written.

**Comment by hawkrives** [comment]
Correct.

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
