### PR TITLE
update fastlane (2.67.0 to 2.71.0)

### PR DESCRIPTION
**Pull request by hawkrives**
no major changes, I believe

### CODE REVIEW

**Review by rye — APPROVED** [review]
We'll see if it breaks anything! 😁

**Comment by hawkrives** [comment]
Indeed!

**Comment by rye** [comment]
Here's the comparison: https://github.com/fastlane/fastlane/compare/2.67.0...2.71.0.

I'm down for trial-by-fire though.

**Comment by hawkrives** [comment]
Lol. I skimmed their release changelogs before I made the Pr though, so I'm … fairly sure it's safe

**Pull request merged**
