### PR TITLE
Add flavor text to Pause ice cream/shake flavors

### PR DESCRIPTION
**Pull request by hawkrives**
They look so lonely, just sitting there with no descriptions.

These are by no means a serious suggestion, but I'd like to get some feedback and start the ball rolling on them.

### CODE REVIEW

**Comment by hawkrives** [comment]
My feedback so far:

> Omg your shake description suggestions
> oh god
> no no no no

so… I'm leaving this open.

**Review by drewvolz — APPROVED** [review]
I now find your descriptions comical. I'm going to approve.

**Comment by hawkrives** [comment]
Well, you're the pause contact, so…

**Comment by drewvolz** [comment]
:+1:

**Pull request merged**
