### PR TITLE
Add dep on react-native-typography and sprinkle it in

### PR DESCRIPTION
**Pull request by hawkrives**
I see this as the start of a wider range of targeted PRs to address things like https://github.com/StoDevX/AAO-React-Native/issues/1235.

Closes https://github.com/StoDevX/AAO-React-Native/issues/2136.

[`react-native-typography`](https://github.com/hectahertz/react-native-typography)

- I gave white backgrounds to FAQ, Legal, Privacy, and Credits
- I tweaked the Credits view to use react-native-typography's styles
- I made `<Markdown/>` use react-native-typography

<details open><summary>Screenshots</summary>

<table>
<tr><th>Screen</th><th>Before</th><th>After</th></tr>
<tr><th rowspan="2">FAQs</th>
<td>screen shot 2018-01-15 at 6 50 27 pm</td>
<td>screen shot 2018-01-15 at 6 47 55 pm</td>
</tr>
<tr>
<td>screenshot_1516063834
</td>
<td>screenshot_1516063681
</td>
</tr>
<tr><th rowspan="2">Legal</th>
<td>screen shot 2018-01-15 at 6 50 43 pm
</td>
<td>screen shot 2018-01-15 at 6 48 12 pm
</td>
</tr>
<tr>
<td>screenshot_1516063843
</td>
<td>screenshot_1516063692
</td>
</tr>
<tr><th rowspan="2">Privacy</th>
<td>
<td>screen shot 2018-01-15 at 6 48 18 pm
</td>
</tr>
<tr>
<td>screenshot_1516063853
</td>
<td>screenshot_1516063706
</td>
</tr>
<tr><th rowspan="2">Credits</th>
<td>screen shot 2018-01-15 at 6 51 17 pm</td>
<td>screen shot 2018-01-15 at 6 48 45 pm</td>
</tr>
<tr>
<td>screenshot_1516063881
</td>
<td>screenshot_1516063730</td>
</tr>
<tr><th rowspan="2">Help</th>
<td>screen shot 2018-01-15 at 6 51 25 pm
</td>
<td>screen shot 2018-01-15 at 6 49 10 pm
</td>
</tr>
<tr>
<td>screenshot_1516063892
</td>
<td>screenshot_1516063765
</td>
</tr>
<tr><th rowspan="2"><code>button[disabled]</code></th>
<td>screen shot 2018-01-15 at 6 51 41 pm</td>
<td>screen shot 2018-01-15 at 6 49 19 pm</td>
</tr>
<tr>
<td>screenshot_1516063896</td>
<td>screenshot_1516063769
</td>
</tr>
</table>
</details>

## Todo

- [x] Android bulleted lists – no padding? tiny bullet?
- [x] Android h1s are huge
- [x] App title in Credits is tiny on Android

### CODE REVIEW

**Review by rye — COMMENTED** [review]
I'm not 100% on this font on iOS, but this is a good idea.

**Comment by hawkrives** [comment]
@rye It's the same font, just scaled up a bit and kerned to match the iOS system typefaces.

**Comment by rye** [comment]
I'll add Android screenshots in a few.

**Comment by rye** [comment]
| screen shot 2018-01-15 at 08 04 21 | screen shot 2018-01-15 at 08 03 47 |
|---|---|
| screen shot 2018-01-15 at 08 03 38 | screen shot 2018-01-15 at 08 03 29 |

**Comment by hawkrives** [comment]
Hokay 

Might want to tone down that h1 font size a bit

**Comment by rye** [comment]
Updated screenshots:

| screen shot 2018-01-15 at 08 15 58 | screen shot 2018-01-15 at 08 15 54 |
|---|---|

**Comment by hawkrives** [comment]
Android bullets need help too

**Comment by hawkrives** [comment]
okay, what's going on with the app title in Credits. bad app title.

**Comment by hawkrives** [comment]
screenshot_1516060851

fixed the credits screen

**Comment by hawkrives** [comment]
I will sort these screenshots into my table up top when I get back to my apartment.

<details><summary>unorganized</summary>
screen shot 2018-01-15 at 6 49 19 pm
screen shot 2018-01-15 at 6 51 17 pm
screen shot 2018-01-15 at 6 48 45 pm
screen shot 2018-01-15 at 6 50 27 pm
screen shot 2018-01-15 at 6 51 41 pm
screenshot_1516063730
screen shot 2018-01-15 at 6 47 55 pm
screenshot_1516063681
screen shot 2018-01-15 at 6 50 43 pm
screenshot_1516063769
screenshot_1516063843
screenshot_1516063881
screen shot 2018-01-15 at 6 48 12 pm
screen shot 2018-01-15 at 6 50 57 pm
screenshot_1516063692
screen shot 2018-01-15 at 6 48 18 pm
screen shot 2018-01-15 at 6 51 25 pm
screen shot 2018-01-15 at 6 49 10 pm
screenshot_1516063706
screenshot_1516063765
screenshot_1516063834
screenshot_1516063853
screenshot_1516063892
screenshot_1516063896
</details>

**Review by rye — APPROVED** [review]
Looks good, pending a passing CI build.

**Comment by hawkrives** [comment]
Screenshots have been updated! Please file issues about more tweaks.

**Pull request merged**
