### PR TITLE
port BuildingHours to SectionList

### PR DESCRIPTION
**Pull request by hawkrives**
No visual differences (I took the "after" shot first in clock time).

Before | After
--- | ---
screen shot 2017-08-05 at 9 44 03 pm | screen shot 2017-08-05 at 9 43 46 pm

### CODE REVIEW

**Review by drewvolz — CHANGES_REQUESTED** [review]
Android is witnessing a red screen, iOS is okay.

1. Open Hours list
2. Select "Stav Hall", "Convenience Store", "Reference Desk" ... (some do function correctly)
3. Error

**Comment by hawkrives** [comment]
Is that not an issue on `master` on Android? I have a hard time believing that this branch introduced that.

**Comment by drewvolz** [comment]
The issue seems to be on both master and this branch.

**Comment by hawkrives** [comment]
Muh. Ok. I'll file an issue; meanwhile, shall we merge this? Since it doesn't change the status quo?

**Review by drewvolz — APPROVED** [review]
👍 :shipit:

**Pull request merged**
