### PR TITLE
bump all version codes to v2.1.0

### PR DESCRIPTION
**Pull request by hawkrives**
accomplished by running `echo 2.1.0 | bundle exec fastlane bump`

### CODE REVIEW

**Review by drewvolz — APPROVED** [review]

**Review by elijahverdoorn — APPROVED** [review]

**Comment by elijahverdoorn** [comment]
I'm going to merge this so I can get the builds going.

**Comment by hawkrives** [comment]
Alright

**Comment by hawkrives** [comment]
I will push a v2.1.0-1 tag

**Comment by hawkrives** [comment]
https://github.com/StoDevX/AAO-React-Native/releases/tag/v2.1.0-1

**Pull request merged**
