### PR TITLE
Add a <Markdown/> component

### PR DESCRIPTION
**Pull request by hawkrives**
> Needs #1354.

This PR adds a new `<Markdown source={} />` component.

When applied to the Important Contacts view, it can do the following:

Before | After
--- | ---
screen shot 2017-08-05 at 4 02 22 pm | screen shot 2017-08-05 at 3 56 00 pm

That is, we can do inline styles, by writing our source files in Markdown!

Inline things, like *emphasis* and even [inline links](https://google.com).

That's right, this allows us to include _links_ into the middle of some _text blocks_, just like on the web.

We can likely do something similar for our other views that need URLs, as well.

---

If you have a component that wants to override the styles of a rendered element – let's say you want to make all the `**bold**` text red.

```js
const styles = StyleSheet.create({
  heading: {color: 'red'},
})

const myComp = ({text}) => 
  <Markdown
    styles={{Strong: styles.heading}} // here's the magic!
    source={text}
  />
```

… you can just pass part of a StyleSheet in, to merge your styles with the default ones.

Locally, I have ported Contacts, Privacy, Legal, FAQs, and the Dictionary to Markdown views. I'll be making PRs for them shortly.

### CODE REVIEW

**Comment by hawkrives** [comment]
> `source/views/components/markdown/selectable.js` has no `@flow` annotation!

… I guess I need to look at that danger rule, since it definitely does have an annotation.

update: now it's gone. huh.

**Review by drewvolz — APPROVED** [review]
👍 :shipit:

**Review by drewvolz — CHANGES_REQUESTED** [review]
#1359 showed that the Markdown component does not have lists/bullet points implemented yet. It would be great to see this in here before this is merged. Please and thank you!

**Comment by hawkrives** [comment]
I have now added the bullet points:

**Review by drewvolz — APPROVED** [review]

**Comment by hawkrives** [comment]
Something in the bundle-data script is failing on the OS X builds:

```
The following build commands failed:
PhaseScriptExecution Bundle\ Data\ Files /Users/travis/Library/Developer/Xcode/DerivedData/AllAboutOlaf-axgziitukyyjlyfvuepevdfannhu/Build/Intermediates/ArchiveIntermediates/AllAboutOlaf/IntermediateBuildFilesPath/AllAboutOlaf.build/Release-iphoneos/AllAboutOlaf.build/Script-6776346D1ECC93FA00C6F018.sh
(1 failure)
[04:23:47]: Exit status: 65
+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.50.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+
[04:23:47]: ▸     at Module.require (module.js:497:17)
[04:23:47]: ▸     at require (internal/module.js:20:19)
[04:23:47]: ▸     at Object.<anonymous> (/Users/travis/build/StoDevX/AAO-React-Native/scripts/bundle-data.js:7:25)
[04:23:47]: ▸     at Module._compile (module.js:570:32)
[04:23:47]: ▸ Command /bin/sh failed with exit code 1
[04:23:47]: 
```

**Review by elijahverdoorn — APPROVED** [review]
This is great. Really makes a lot more possible for us. Nice work!

**Comment by drewvolz** [comment]
I've made a fix for an older version of node which @hawkrives pointed out that node 8 supports trailing function commas. So we used to bump the node version correctly on iOS. We'll see about upping our node version and then reverting the trailing comma commit.

**Comment by hawkrives** [comment]
@drewvolz time to revert https://github.com/StoDevX/AAO-React-Native/pull/1356/commits/a6040a77ea0b20b71f3516a9a57ddde87618fed6?

**Comment by drewvolz** [comment]
Reverted.

**Comment by hawkrives** [comment]
thank ya!

**Pull request merged**
