### PR TITLE
Add more log parsing to Danger

### PR DESCRIPTION
**Pull request by hawkrives**
This PR is half a PR and half a Danger test.

If this works properly, Danger will now comment on PRs with the actual build failures (for the JS build, at least.)

🤞

### CODE REVIEW

**Comment by drewvolz** [comment]
We really should trim the output of the danger parsing. I like where this is going!

**Comment by hawkrives** [comment]
Ignore this; I'm testing colors.

<span style="color: red">red</span> and black.

<font color="#ffffff">red?</font>

**Comment by drewvolz** [comment]
**Testing:**

<span style="color: red">red</span> and black.

- #f03c15 `#f03c15`
- #c5f015 `#c5f015`
- #1589F0 `#1589F0`

<a></a>

**Comment by hawkrives** [comment]
Danger has now been sated. I want to merge this after the builds pass.

**Review by drewvolz — APPROVED** [review]
:+1: :shipit:

**Pull request merged**
