### PR TITLE
Fix Landscape stuffs

### LINKED ISSUE #1386: Landscape home screen edit needs work
Need to adjust width of the view after each rotation

edit-home-landscape

### LINKED ISSUE #1460: Landscape homeview funkiness
Odd behavior if the app is launched in landscape. I'd expect for the views to be the 2:3 column layout instead of the 1:2 column layout.

~ | Portrait | Landscape
--|--|--
Start Portrait (expected) |  d0363b38-f484-4bee-b840-133e960240d5 | 8e70b23a-bd8c-46d5-9ff8-e26a9e93ae8c
Start Landcape | 5b4ac978-722c-44cf-8de1-74800bc5030a | 0249b269-1aa0-4473-ad50-b43501e7e81d

### PR DESCRIPTION
**Pull request by hawkrives**
From the [React Native docs](https://facebook.github.io/react-native/docs/dimensions.html#get):

> Note: Although dimensions are available immediately, they may change (e.g due to device rotation) so any rendering logic or styles that depend on these constants should try to call this function on every render, rather than caching the value (for example, *using inline styles rather than setting a value in a StyleSheet*).

(emphasis mine.)

As you will note here, we were _literally_ doing the opposite of the recommended practice.

Closes #1386
Closes #1460

---

For HomeScreen, I changed it to render two columns, which allows RN's flexbox code to properly size the items to be next to each other. This way, RN can update just the layout without triggering an entire render.

For Edit and Webcams, I listen for the device's screen change size event, and pass the width from that on down, so that the views re-render when the device rotates.

---

Home | Before | After
--- | --- | ---
portrait | screen shot 2017-09-14 at 11 20 46 pm | screen shot 2017-09-14 at 11 25 26 pm
portrait,<br>rotated | screen shot 2017-09-14 at 11 20 50 pm | screen shot 2017-09-14 at 11 25 29 pm
landscape |screen shot 2017-09-14 at 11 21 20 pm | screen shot 2017-09-14 at 11 25 34 pm
landscape,<br>rotated |screen shot 2017-09-14 at 11 21 24 pm | screen shot 2017-09-14 at 11 25 37 pm

Edit | Before | After
--- | --- | ---
portrait | screen shot 2017-09-14 at 11 22 09 pm | screen shot 2017-09-14 at 11 25 54 pm
portrait,<br>rotated | screen shot 2017-09-14 at 11 22 20 pm | screen shot 2017-09-14 at 11 25 51 pm
landscape | screen shot 2017-09-14 at 11 22 28 pm | screen shot 2017-09-14 at 11 25 46 pm
landscape,<br>rotated |  screen shot 2017-09-14 at 11 22 31 pm | screen shot 2017-09-14 at 11 25 43 pm

Webcams | Before | After
--- | --- | ---
portrait | screen shot 2017-09-14 at 11 23 34 pm | screen shot 2017-09-14 at 11 26 01 pm
portrait,<br>rotated |screen shot 2017-09-14 at 11 23 37 pm | screen shot 2017-09-14 at 11 26 03 pm
landscape |screen shot 2017-09-14 at 11 23 53 pm | screen shot 2017-09-14 at 11 26 09 pm
landscape,<br>rotated |screen shot 2017-09-14 at 11 24 11 pm | screen shot 2017-09-14 at 11 26 11 pm

### CODE REVIEW

**Comment by hawkrives** [comment]
Oh, mumble grumble, flow.

**Comment by drewvolz** [comment]
Hmm.. starting off each view [home, edit, ksto, webcams] in landscape and then rotating, I'm not seeing different behavior prior to this PR.

**Comment by hawkrives** [comment]
So the reason why there's no difference … is because React's not re-rendering the views when we rotate.

I'm not sure how to make it do so, or if that's a good idea.

**Comment by drewvolz** [comment]
What about storing the dimensions in state and getting react to re-render when those change?

**Comment by hawkrives** [comment]
I'd rather store it in redux, so that we don't have to add the event listeners to every screen that needs something special for landscape mode. 

Turns out that Dimensions has addEventListener, so we can use that.

**Comment by drewvolz** [comment]
Redux + dimensions event listeners sound good to me :+1:

**Comment by drewvolz** [comment]
Excellent work! I'm fine with merging this. It is a _huge_ improvement over the current implementation. We will have _one_ detail to look at... starting in portrait and rotating to landscape in "Edit Home".

But wow. Wow! You've improved it many, many times over.

android-after

**Review by drewvolz — APPROVED** [review]

**Comment by hawkrives** [comment]
@drewvolz Would you mind filing a new issue in v2.4 for https://github.com/StoDevX/AAO-React-Native/pull/1474#issuecomment-329681471, please?

**Pull request merged**
