### PR TITLE
Version 2.5.0, β2

### PR DESCRIPTION
**Pull request by rye**
View [the comparison from v2.4.1](https://github.com/StoDevX/AAO-React-Native/compare/v2.4.2...v2.5.0-beta.1).
View [the comparison from v2.5.0-beta.1](https://github.com/StoDevX/AAO-React-Native/compare/v2.5.0-beta.1...v2.5.0-beta.2).

## Checklist
- [x] [Release PR]() successfully builds against `master` ([follow on Circle](https://circleci.com/workflow-run/f921672e-22de-4389-a793-90f560c9a2ab))
- [x] Signed-off/approved
- [x] GitHub release notes drafted ([wiki](https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes#v250))
- [x] [Release PR]() merged to `master`.
- [x] GitHub release created
- [ ] Tag build passes ([follow](https://travis-ci.org/StoDevX/AAO-React-Native/builds/329315742))

### CODE REVIEW

**Comment by rye** [comment]
@stodevx-bot 💯

**Comment by hawkrives** [comment]
269 commits since beta 1???

**Comment by rye** [comment]
Yeah, triple the movement since v2.4.2.  Lots of stuff changed, apparently!

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
I don't think we'll see the Travis build start until the morning. 

There are close to 2,000 jobs in the queue, and they're only running 90 workers.

**Comment by rye** [comment]
I think we'll merge tonight; tag build shouldn't get cancelled as a result.  Then we have beta in master and we can rest easy.

Android deployed fine.

**Pull request merged**
