### PR TITLE
Building hours

### PR DESCRIPTION
**Pull request by elijahverdoorn**
UI changes
yellow border for  "closing soon"
fix logic

### CODE REVIEW

**Comment by hawkrives** [comment]
Do you want an actual code review? 😜

**Comment by elijahverdoorn** [comment]
Nah, this is mostly for me to keep track of what I still have to do. If you
want to comment feel free.

**Comment by hawkrives** [comment]
My main comment is that I really like using `let`. I can see no reason to use `var` in modern, fresh JS code.

The problem with `var` is that it's quirks pop up when you don't expect them, and `let` fixes most (all ?) of them.

**Comment by hawkrives** [comment]
I guess I never added `no-var` to the eslint config.

**Comment by elijahverdoorn** [comment]
This is done, I merged the stuff that @hawkrives did to it into this branch, so no major changes to that code other than to add the yellow border for buildings closing soon, also added the images from my trip to campus on 8/5. Closing issue #18.

**Pull request merged**
