### PR TITLE
🔍 Searchable food menus

### LINKED ISSUE #2388: Search courses by description?
Followup from #2341 and #2383 

@hawkrives:

> I feel like searching description is going to generate false positives and be really slow.
>
> I'd like some benchmarks on search speed with and without description searching.
>
> Nothing fancy; just, like, log `performance.now` before and after the filter process happens.

### LINKED ISSUE #3523: Searchable menus
From a user:

> It would be nice to be able to search within a menu (e.g. The Cage) to find items by name!

(This might fit under an existing issue; "Related Issues" didn't find anything.)

Thoughts?

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #3523.

This PR makes the menu titles and descriptions on iOS and Android searchable.

### CODE REVIEW

**Comment by hawkrives** [comment]
I will request to block this on a redesign of the menus screen. 

In my opinion, having Navigation > MenuInfo > FilterableItems > ActiveFilters > SearchBar (in whatever order) is too much for one screen. 

I do want to be able to search, but I am against just adding a search bar here.

**Comment by drewvolz** [comment]
> In my opinion, having Navigation > MenuInfo > FilterableItems > ActiveFilters > SearchBar (in whatever order) is too much for one screen.

This is not the case while searching.

**Comment by hawkrives** [comment]
But it is the case when you're scrolling, before you search. If you ever search; not every visit to the menu will involve a search.

**Comment by drewvolz** [comment]
> But it is the case when you're scrolling, before you search.

Search and filters are not sticky.

**Comment by drewvolz** [comment]
This is not the case while scrolling regardless of searching, on both platforms.

**Comment by drewvolz** [comment]
It’s also not the case while searching because filters are hidden while searching.

**Review by hawkrives — CHANGES_REQUESTED** [review]
I will request to block this on a redesign of the menus screen.

In my opinion, having Navigation > MenuInfo > FilterableItems > ActiveFilters > SearchBar (in whatever order) is too much for one screen.

I do want to be able to search, but I am against just adding a search bar here.

(just moving to an official review-comment comment)

**Comment by drewvolz** [comment]
What do you suggest @hawkrives

**Comment by drewvolz** [comment]
My first thought is to add a `headerRight` option to the menu screens, so that lands us at

```js
MenusView.navigationOptions = {
	title: 'Menus',
	headerRight: <SearchButton />,
}
```

where `SearchButton` looks _something_ like this

```js
type Props = {
	onSearch: () => mixed,
	searching: boolean,
}

export function SearchButton(props: Props) {
    const icon = `${Platform.OS === 'ios' ? 'ios' : 'md'}-search`
	return (
		<Touchable
			highlight={false}
			onPress={props.onSearch}
			style={styles.button}
		>
			<Icon name={icon} style={styles.icon} />
		</Touchable>
	)
}
```

but that leads to a tricky situation where we don't have the menu view's right button in communication with the view it's acting on. I'm thinking of then storing whether we've tapped that a button inside redux so that I can handle view changes to show/hide one of search, active filters, filterable items, or menu info as appropriate. 

The goal would be to show search IFF the nav button for search is tapped and hide the rest and reverse when the "cancel" button is tapped on the search bar.

Do we go the redux route? I'd like to get an MVP search into the menu as it was a feature directly requested by one of our users, so advice and suggestions from you would be appreciated.

**Comment by hawkrives** [comment]
I do not have a suggestion. I just know that I'm opposed to _ever_ having 5 rows of stuff before the content appears, whether or not it persists when you scroll.

**Comment by hawkrives** [comment]
(Also, I don't know if this changes the calculus, but the person who requested this is a friend and a coworker. He's understanding of taking time to do things right.)

**Comment by drewvolz** [comment]
> I do not have a suggestion. I just know that I'm opposed to ever having 5 rows of stuff before the content appears, whether or not it persists when you scroll.

It's 4, is that okay? While not everyone uses the filters, that would make it 3 if you're browsing the menu. I'll mention this is the same amount of things that appear on course searching with filters activated.

**Comment by drewvolz** [comment]
@hawkrives I don't think we're going to have a change to our overall navigation anytime soon. Thoughts on if this should be closed since it won't be accepted?

**Comment by drewvolz** [comment]
Closing this out until it can resolve the concerns about navigation items. Perhaps we can take the approach GH takes with their issue/PR list in the future.

**Pull request closed without merging**
