### PR TITLE
Add Holland Hall hours

### PR DESCRIPTION
**Pull request by hawkrives**
These will likely change in a week or two, as the building gets used.

I will update them when I get the new hours.

### CODE REVIEW

**Review by drewvolz — APPROVED** [review]

**Comment by hawkrives** [comment]
I couldn't come up with a better way to do the Closed-on-Saturday bit (because it's closed on Saturday for whatever reason), so I just left it out.

That led me to file #1516.

**Comment by drewvolz** [comment]
Isn't adding something that's closed as trivial as omitting hours for that day?

**Comment by drewvolz** [comment]
...and that's exactly what you did. So you want a way to _say_ it's closed instead of hiding that day.

**Comment by hawkrives** [comment]
Yes. To be more explicit about a lack of hours on that day.

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
