### PR TITLE
Viewport width styles on toolbar

### LINKED ISSUE #2772: FilterToolbar's minimum width is not 100% of the screen width
See the border below the Specials Only button.

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #2772

**Before** | **After Portrait**
--|--
 | portrait

**After Landscape**

landscape

### CODE REVIEW

**Comment by hawkrives** [comment]
Just to put it on GitHub: 

> @drewvolz Try using flex / percentages before Viewport to fix the width

**Review by hawkrives — APPROVED** [review]

**Comment by drewvolz** [comment]
Oh shoot, that's not a full-solution yet. Hold off on merging.

image

**Comment by drewvolz** [comment]
Any opposition to reverting back to `viewport`? Having a difficult time getting anything else to behave.

**Comment by hawkrives** [comment]
Closed by #2777

**Pull request closed without merging**
