### PR TITLE
Add a "meal switcher" to the menus

### PR DESCRIPTION
**Pull request by hawkrives**
This addresses a user comment from this morning:

> I want to be able to see the lunch and dinner options at all times of the day. 

So. Now, to switch between menus for the day, open the Filter screen, and pick a menu.

I have not yet tested this on Android.

### CODE REVIEW

**Comment by hawkrives** [comment]
So um. The build that failed? Was the iOS build.

https://travis-ci.org/StoDevX/AAO-React-Native/jobs/203081814#L3547: 
> /Users/travis/build/StoDevX/AAO-React-Native/node_modules/react-native-google-analytics-bridge/ios/RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge/RCTGoogleTagManagerBridge.h:2:9: 'TAGContainer.h' file not found

WTF? I guess I'll tell it to rebuild the build in the morning, or we can merge it and hope that the google analytics bridge didn't just break all of our builds.

**Edit:** I restarted the iOS build. We'll see if it goes green.

**Comment by drewvolz** [comment]
I would say :shipit: but we're not sure what is going on with `TagContainer.h`?

**Comment by hawkrives** [comment]
@drewvolz Can you build it locally?

**Comment by drewvolz** [comment]
Yes

**Comment by hawkrives** [comment]
The `TagContainer.h` thing is really weird, but since we can both build locally, I think we should merge and then if it continues to be weird I'll either revert this (and fix it) or just fix it.

**Comment by hawkrives** [comment]
Fixed it.

**Pull request merged**
