### PR TITLE
Hack around the android map issue

### PR DESCRIPTION
**Pull request by elijahverdoorn**
Someday we'll fix this, but until then we need something that works so
that we can ship a first version.

### CODE REVIEW

**Comment by elijahverdoorn** [comment]
Not meant to close it, but referencing #27

**Comment by hawkrives** [comment]
I like it. If the builds pass, :shipit:!

**Comment by hawkrives** [comment]
I'll move #27 to the `next` milestone then.

**Comment by elijahverdoorn** [comment]
It's the same linter error that @hawkrives agreed to fix, so I'm merging.

**Comment by hawkrives** [comment]
ok but you could fix it sooner than I can :P

just add `schedule: React.PropTypes.any,` to propTypes in busLine.js

**Comment by hawkrives** [comment]
i'll update the proptype to actual typing info later

**Comment by hawkrives** [comment]
oh fine I'll add it

**Comment by hawkrives** [comment]
see #132

**Pull request merged**
