### PR TITLE
danger: Add a rule to check whether or not the CHANGELOG was updated

### PR DESCRIPTION
**Pull request by rye**

### CODE REVIEW

**Comment by rye** [comment]
Maybe I should update my regex to `/\.js$/`?

**Comment by rye** [comment]
Good job, Danger! A correct assessment of this PR. I shall make a change to the CHANGELOG.

In all seriousness, the "Enforce Changelogs" example on https://danger.systems/js/ is a much simpler approach. It would also potentially enable a "trivial" label to be added to PRs that don't matter.

However, I think checking _which_ files were changed is also a good thing, since I don't think we really need to note e.g. data or dep changes in the changelog.

**Comment by rye** [comment]
In order to preserve linear history, we should merge #3177 before this one.

**Review by hawkrives — DISMISSED** [review]

**Review by hawkrives — DISMISSED** [review]

**Review by hawkrives — APPROVED** [review]
donk

**Comment by rye** [comment]
Mergey mergey.

**Pull request merged**
