### PR TITLE
Add [tool/renovate] label to renovate PRs

### PR DESCRIPTION
**Pull request by hawkrives**
as per comment in #3201

### CODE REVIEW

**Comment by hawkrives** [comment]
I guess, should we use `tool/renovate`, or make a different label?

**Comment by rye** [comment]
I added `tool/renovate` when dealing with the configuration.  Maybe just `renovate`, with one of Renovate's primary colors as its color?

**Comment by hawkrives** [comment]
SGTM

**Comment by hawkrives** [comment]
image

proposal

**Comment by rye** [comment]
Looks good. ~Why did you apply that to this PR?~ Oh, it makes it visible. Looks good.

**Review by rye — APPROVED** [review]

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
