### PR TITLE
Remove coveralls from CircleCI config

### PR DESCRIPTION
**Pull request by drewvolz**
> at least it's not a 503 today

We're hitting a 405 on our PRs, so let's say goodbye for now.

### CODE REVIEW

**Comment by drewvolz** [comment]
I checked to see the usage with ripgrep after this commit.

```
$ rg -i coveralls --iglob=[!./node_modules] ./*

./CHANGELOG.md
89:- Removed coveralls coverage reporting
```

**Comment by rye** [comment]
Would it be worth replacing with codecov?

**Comment by drewvolz** [comment]
I think it'd be nice to have a replacement. Would it make sense to have that be a follow-up to this PR instead of as a part of this?

**Comment by rye** [comment]
I think that'd be suited to go into this PR

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
