### PR TITLE
Fix sis view

### LINKED ISSUE #170: Settings keyboard dismissal
The keyboard for logging in to SIS does not dismiss if the Login button is tapped instead of the Done button on the keyboard.

screen shot 2016-08-23 at 8 34 41 am

### LINKED ISSUE #182: SIS switched to Google OAuth
SIS login is broken, we cannot login at the moment with OAuth being the authentication method. This is a shipping issue for the SIS functionality. #177 

How do we make sure the user can login with OAuth? 
- [The link that contains the link below](https://www.stolaf.edu/sis/login.cfm)
- https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fas%3Da97492d886b731b%26scope%3Dhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%2Bemail%26response_type%3Dcode%26redirect_uri%3Dhttps%3A%2F%2Fwww.stolaf.edu%2Fsis%2Flogin.cfm%26state%26hd%3Dstolaf.edu%26from_login%3D1%26client_id%3D368607578799-f5geh8k6l3km5et1ufbtusikso5sb7rj.apps.googleusercontent.com&btmpl=authsub&hd=stolaf.edu&sacu=1&scc=1&rip=1#identifier

### PR DESCRIPTION
**Pull request by hawkrives**
~~Merge #191 first.~~

This is an attempt at fixing the SIS data loading when the cookie expires.

Closes #182.
Closes #170.

### CODE REVIEW

**Comment by drewvolz** [comment]
@elijahverdoorn we're trying to fix this and we need you to take a look at it.

The end goal is so that "you should be able to open the courses view and get the 'please log in' view when we do not have credentials after logging in, or an invalid token."

screen shot 2016-09-01 at 9 31 32 am
1.  Log out and log back in through Settings so that you see Sign In
   
    
2.  One idea @hawkrives had was in `sis/courses.js` lines 70-76 where we comment out everything but the fetch, or alternatively, take out everything but the `this.fetchData` call.
   
    Option one
   
   ```
      componentWillMount() {
        //this.checkLogin().then(shouldContinue => {
        //  if (shouldContinue) {
            this.fetchData()
        //  }
        //})
      }
   ```
   
    Option two
   
   ```
      componentWillMount() {
            this.fetchData()
      }
   ```
3. Go ahead and look at the SIS Courses view. Play with it. The courses loaded a blank view with spinner for me, I clicked off to the balances, then back on. Then the courses loaded, and now the spinner is still there. We haven't played with it enough and need another set of eyes and ideas.
   
    screen shot 2016-09-01 at 9 32 56 am

@hawkrives also managed to get the tabs back in there... they are important. So if you are editing this on iOS for example, the warnings may cover them, but now you know they are there.

screen shot 2016-09-01 at 9 30 17 am

**Comment by drewvolz** [comment]
I think I have a fix... flipping the order of operations to have the `loggedIn` check before the loading screen as shown here displayed the appropriate view.

```
   if (!this.state.loggedIn) {
      return <ErrorView route={this.props.route} navigator={this.props.navigator} />
    }

    if (this.state.loading) {
      return <LoadingScreen />
    }
```

### This does not completely fix it, though.

Still have to get the courses to load properly. So... `loadAllCourses` is misbehaving? Need it to stop the refreshing animation and get the data.

**Comment by elijahverdoorn** [comment]
I can test this tomorrow, I'm really busy over the next few days.

**Comment by hawkrives** [comment]
We'll do some more testing tonight JST, probably. We're not comfortable that it solves everything yet, either.

But more testing is always good.

**Comment by hawkrives** [comment]
I fixed the course loading. I'm pretty sure it's working now, with one note.

That note is as follows:

> After you log in via the settings view from the "You Haven't Logged In" button, as opposed to the Settings view proper, when you return to the SIS view, the screen does not refresh.

I have an idea.

**Comment by hawkrives** [comment]
I'm going to try and borrow the callback fix from the Settings view.

**Comment by hawkrives** [comment]
There. I'm pretty confident in this PR now.

**Comment by drewvolz** [comment]
Thank you, @hawkrives! That's exactly what we needed.

**Comment by elijahverdoorn** [comment]
Works for me!

**Pull request merged**
