### PR TITLE
Allow for iPads

### PR DESCRIPTION
**Pull request by elijahverdoorn**
It's better to have the app scaled up than to use an iPhone app on the iPad.

### CODE REVIEW

**Comment by hawkrives** [comment]
Drew and I will need to test this before merging. We will need to ensure that there are no remaining screen size assumptions – we've found at least four so far, only noticeable when switching screen sizes.

say, on a 5s when the screen was designed on a 6+.

**Comment by drewvolz** [comment]
The justified text might be something we want to deal with.

**Comment by hawkrives** [comment]
Ooh, good catch. Max-width on the text?

**Comment by elijahverdoorn** [comment]
This is something that I'm not expecting for v2.0.0, just something that I've been trying. Thanks for finding the issues, I'd be happy to fix them if you post them here.

**Comment by hawkrives** [comment]
Oh, ok. Yeah, we'll do an audit after v2 is released.

**Comment by elijahverdoorn** [comment]
Closing this since it's old and we're not really ready. Another effort will be made in the future.

**Review by drewvolz — APPROVED** [review]
Let’s explore making it look good on iPad!

**Review by hawkrives — APPROVED** [review]
@elijahverdoorn I've decided that I agree with your original sentiment: it's nice to let it scale up. 

I've also convinced Drew that this is the first step to doing anything with iPad. 

As such, let's merge this baby!

**Pull request merged**
