### PR TITLE
Publish Gradle build scans automatically (and accept Gradle's TOS in CI)

### PR DESCRIPTION
**Pull request by hawkrives**
I've got the Android Build task set up to auto-publish Gradle scans, but we need to accept the Gradle TOS. I've now got that configured to only happen on CI.

Published Gradle scans expire after 90 days.

### CODE REVIEW

**Comment by drewvolz** [comment]
- A Build Scan that has not been viewed within 3 months of being created will be removed.
- Once a Build Scan has been viewed, it will be available indefinitely.

This sounds good, we can delete the ones we've viewed and let the ones we do not need expire.

**Review by drewvolz — APPROVED** [review]

**Comment by hawkrives** [comment]
Oh, that's more nuanced than I realized:

image

**Comment by hawkrives** [comment]
This is supposed to only publish on failure. It is publishing on all builds…

maybe because they include deprecations???

**Comment by hawkrives** [comment]
I wonder if `--scan` is overriding publishOnFailure?

I'd rather publish all of them than none of them, so if I haven't figured this out by ~Monday I'll plan to merge this as-is.

**Comment by hawkrives** [comment]
@drewvolz is pretty sure, after digging, that `--scan` overrides the publishOnFailure command inside the gradle file. Let's see!

**Comment by hawkrives** [comment]
I don't care anymore - let's just always upload it… Gradle's the one paying for the hosting, and they expire after 90 days anyway

**Comment by hawkrives** [comment]
Thinking about this more, I would rather publish all scan logs - this way, if a single job is slow, we can dig in right away and see why.

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
