### PR TITLE
Rename CMIE to Taylor Center

### PR DESCRIPTION
**Pull request by drewvolz**
We received a suggestion to rename the CMIE to the Taylor Center

### CODE REVIEW

**Review by hawkrives — COMMENTED** [review]
Should we rename the subtitle to Taylor Center for … 

?

**Comment by drewvolz** [comment]
I wanted to ask that here. It seemed redundant but I'm not sure.

**Comment by rye** [comment]
I'd say the subtitle should be the full name, "Taylor Center for Equity and Inclusion"?

It's a bit redundant and it might look weird but it's probably the best possible choice.

**Comment by hawkrives** [comment]
Yeah. I'd treat it like Piper Center - it's never abbreviated to "Center for Vocation and Career".

**Comment by drewvolz** [comment]
If it’s not an acronym and we’re not providing additional context for something, what do you all think of simply removing the subtitle here, like we do elsewhere?

**Comment by hawkrives** [comment]
I would be fine with not having a subtitle here, since it's not an acronym anymore

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
idk, Piper Center is just called Piper Center… don't know if we need the full name on Taylor

**Pull request merged**
