### PR TITLE
First version of the settings menu

### PR DESCRIPTION
**Pull request by drewvolz**
- Added the settings page when the info icon is pressed (maybe should change to gear for settings)
- Added `react-native-tableview-simple` so that we can simply create stylized tables and cells
- Added the credentials fields (username/password) for app-wide login. Currently saves with `react-native-keychain`. Able to add, edit, and delete logins/passwords. At the moment, they save when both username and password are present, and only when 'Done' is hit on the password.
- Added the rows to launch views for support, version, credits, legal, and privacy policy
- Added email function using `react-native-communications` for support to `odt@stolaf.edu`
  settings

### CODE REVIEW

**Comment by hawkrives** [comment]
I don't think we necessarily need to change the icon – it's more info than settings right now, no? :P

But I also see the want to change it. I care not.

**Comment by hawkrives** [comment]
(this is part of #23)

**Comment by drewvolz** [comment]
Right. It is a negligible change. Thinking about how to route the user to this view, I remember @elijahverdoorn mentioned he wanted certain portions of the app unlocked to everyone, so that cuts out making the user log-in from the start. So if they enter the SIS portion of the app, do we immediately route them to the Settings view?

We could present a button saying 'Let's get started' in the SIS view, and have that route them to the Settings so that it is hopefully less confusing. Thoughts?

**Comment by elijahverdoorn** [comment]
Everyone should be able to use the app, regardless of if they have a St. Olaf account or not. I am planning on implementing an "intro" screen using this https://github.com/FuYaoDe/react-native-app-intro , what if we had the option to input username and password there (skippable) and also in the settings? If they start the SIS view without having a valid username and password then we can just display a message and link to the settings view for them to enter it.

As for the icon, I'd prefer a gear.

**Comment by hawkrives** [comment]
aao sis

This is something along the lines of what I'm thinking. I'm all for letting anyone use the app and putting as little as possible behind the auth barriers.

I'm thinking something along the lines of,

```
<username>
<password>

<short paragraph about why we need olaf credentials for this part of the app>
```

Once you've logged into one section, we share your credentials to the other sections.

**Comment by drewvolz** [comment]
Note: need to add user data to support email using [react-native-device-info](https://github.com/rebeccahughes/react-native-device-info)
- Manufacturer
- Model
- ID
- System Name
- Device Version
- App Version
- Build Number

**Pull request merged**
