### PR TITLE
Update react-native-popover-view to v1.0.7

### PR DESCRIPTION
**Pull request by hawkrives**
Closes #2874

### CODE REVIEW

**Comment by hawkrives** [comment]
We may also need to add the react-navigation package: https://github.com/SteffeyDev/react-native-popover-view/issues/17#issuecomment-415937923

**Comment by hawkrives** [comment]
Looking through https://github.com/SteffeyDev/react-navigation-popover, I don't think we need that.

**Comment by hawkrives** [comment]
image

Works. Yay.

**Comment by hawkrives** [comment]
Also, it _might_ have fixed https://github.com/SteffeyDev/react-native-popover-view/issues/2… I think

**Review by rye — APPROVED** [review]

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
