### PR TITLE
bump version for v2.1.1

### PR DESCRIPTION
**Pull request by hawkrives**
We should merge this after @elijahverdoorn has built and submitted the binaries for v2.1.0

> `echo v2.2.0 | bundle exec fastlane bump`

### CODE REVIEW

**Comment by elijahverdoorn** [comment]
I guess I'd wait on this in case we think we need a 2.1.1 to fix some breaking bug. I'd rather the version number only go up. I'm making a document about the release process and after forgetting twice I have the version number paragraph bolded.

**Comment by hawkrives** [comment]
```console
$ echo v2.1.1 | bundle exec fastlane bump
```

**Comment by hawkrives** [comment]
@elijahverdoorn Changed to v2.1.1

**Review by mattk410 — APPROVED** [review]
Nice work!

**Pull request merged**
