### PR TITLE
[Viewport] useWindowDimensions hook instead of viewport

### PR DESCRIPTION
**Pull request by drewvolz**
React native provides a [`useWindowDimensions`](https://reactnative.dev/docs/usewindowdimensions) hook which, well, I'll let it speak for itself.

> useWindowDimensions is the preferred API for React components. [(instead of Dimensions)](https://reactnative.dev/docs/dimensions)
>
> Unlike Dimensions, it updates as the window's dimensions update. This works nicely with the React paradigm. It automatically updates width and height values when screen size changes.

<br />

Modules that depend upon this are: 
~|~
--|--
notice | ✅  manually checked
searchbar | ✅  manually checked
radio | ✅  manually checked
webcams | ✅  manually checked

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]
Dang! Nice. 

As a follow-up, what do you think about … removing `<Viewport/>` entirely, and just putting "useWindowDimensions" into the four spots that use Viewport?

**Comment by drewvolz** [comment]
I considered that option initially but was unsure if we would see more benefits from **not** centralizing this as an abstraction. Do we prefer to remove our Viewport component instead of updating Viewport?

**Comment by hawkrives** [comment]
I think I'd prefer to remove Viewport

**Comment by drewvolz** [comment]
Okay! The idea to nix viewport cascaded into a few more changesets.

I think we can go with this order: 

1. Review and merge these child PRs into this branch (`fix-viewport`)
* #5985,
* #5986,
* #5987,
* #5988
2. #5983
Refactor `fix-viewport` to completely remove the remaining references to the `<Viewport />` module.
  That changeset is done but has not been pushed to this branch. That will happen after step one.
 
  <details>
  <summary>📝Diff for step 2</summary>
  
```diff
  diff --git a/modules/filter/package.json b/modules/filter/package.json
index 19ac3c0b7..8d43e1939 100644
--- a/modules/filter/package.json
+++ b/modules/filter/package.json
@@ -21,7 +21,6 @@
     "@frogpond/layout": "^1.0.0",
     "@frogpond/tableview": "^1.0.0",
     "@frogpond/touchable": "^1.0.0",
-    "@frogpond/viewport": "^1.0.0",
     "lodash": "^4.17.21"
   }
 }
diff --git a/modules/viewport/index.ts b/modules/viewport/index.ts
deleted file mode 100644
index 1de54eb91..000000000
--- a/modules/viewport/index.ts
+++ /dev/null
@@ -1,10 +0,0 @@
-import {ScaledSize, useWindowDimensions} from 'react-native'
-
-type Props = {
-	render: (dimensions: ScaledSize) => JSX.Element
-}
-
-export let Viewport = (props: Props): JSX.Element => {
-	let viewport = useWindowDimensions()
-	return props.render(viewport)
-}
diff --git a/modules/viewport/package.json b/modules/viewport/package.json
deleted file mode 100644
index 89365df91..000000000
--- a/modules/viewport/package.json
+++ /dev/null
@@ -1,15 +0,0 @@
-{
-  "name": "@frogpond/viewport",
-  "version": "1.0.0",
-  "description": "",
-  "main": "index.ts",
-  "author": "",
-  "license": "ISC",
-  "scripts": {
-    "test": "jest"
-  },
-  "peerDependencies": {
-    "react": "^17.0.0",
-    "react-native": "^0.68.0"
-  }
-}
diff --git a/package-lock.json b/package-lock.json
index 1cdce0263..9775b6091 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -295,7 +295,6 @@
         "@frogpond/layout": "^1.0.0",
         "@frogpond/tableview": "^1.0.0",
         "@frogpond/touchable": "^1.0.0",
-        "@frogpond/viewport": "^1.0.0",
         "lodash": "^4.17.21"
       },
       "peerDependencies": {
@@ -20741,7 +20740,6 @@
         "@frogpond/layout": "^1.0.0",
         "@frogpond/tableview": "^1.0.0",
         "@frogpond/touchable": "^1.0.0",
-        "@frogpond/viewport": "^1.0.0",
         "lodash": "^4.17.21"
       }
     },
```

  </details>

**Review by rye — APPROVED** [review]

**Pull request merged**
