### PR TITLE
Enable IT Helpdesk tools

### PR DESCRIPTION
**Pull request by drewvolz**
Part of #2404

This enables the tool but does not change the wording as #2404 requests. I am unsure what Heather would like to change the wording to (@hawkrives)

### CODE REVIEW

**Comment by hawkrives** [comment]
Heather didn't have any opinions on the wording.

I like whimsy in my projects, which is why I wrote what I originally did in here.

If people start submitting tickets without editing the information, we can always change it remotely.

So… I care not. Ideas?

**Comment by drewvolz** [comment]
I would encourage us to make it blank so that the email client pokes the user into setting a subject of their own.

**Comment by hawkrives** [comment]
I don't think that will encourage people to set a subject, but whatevs.

**Comment by hawkrives** [comment]
I would _strongly prefer_ to have a subject of some sort.

**Comment by drewvolz** [comment]
We can change it if it is a problem in the future. Okay?

**Comment by hawkrives** [comment]
😜

**Review by hannesmcman — APPROVED** [review]

**Pull request merged**
