### PR TITLE
Update building hours per published Interim building schedule

### PR DESCRIPTION
**Pull request by rye**
- I verified and updated hours in accordance with [the Public Safety schedule][1].
- I verified the hours for Rolvaag against [the library's site][2].
- No change to Cage hours.
- Updated Stav Hall hours per [the CafeBonAppetit site][3] (dinner, lunch close earlier during Interim)

[1]: https://wp.stolaf.edu/publicsafety/files/2019/11/201920AcademicBldgHrsInterim.pdf
[2]: https://www.stolaf.edu/library/libinfo/hours.cfm
[3]: https://stolaf.cafebonappetit.com/cafe/stav-hall/

### CODE REVIEW

**Comment by rye** [comment]
Looks like our tests will be probably be failing for a week or so.

**Review by drewvolz — APPROVED** [review]
Ignoring tests, RSLGTM. Thanks, @rye!

**Comment by rye** [comment]
Build failures are due to unrelated breakage that seems to always happen right around the turn of the year.

Merging now; deployment does not require tests to pass.

**Comment by drewvolz** [comment]
testing notifications @rye

**Pull request merged**
