### PR TITLE
hours: Update bookstore hours per user submission

### PR DESCRIPTION
**Pull request by rye**
Verified. Sunday hours are C-store only but otherwise this should be correct.

### CODE REVIEW

**Comment by hawkrives** [comment]
Don't we have the convenience store as a separate section?

**Comment by rye** [comment]
Here's the hours from [stolaf.bncollege.com](https://stolaf.bncollege.com/webapp/wcs/stores/servlet/BNCBLocationAndContactView?storeId=88916&langId=-1&catalogId=10001)

image

**Comment by rye** [comment]
Fixed.

**Comment by drewvolz** [comment]
> Don't we have the convenience store as a separate section?

Correct

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
