### PR TITLE
Change SARN website back to pages

### PR DESCRIPTION
**Pull request by drewvolz**
> Hawken: I have now moved most of SARN back to pages (at their request)

### CODE REVIEW

**Review by rye — APPROVED** [review]

**Comment by hawkrives** [comment]
I will merge this when SARN has approved the new website.

**Comment by drewvolz** [comment]
The URL on A-Z is updated. Can this be merged?

**Comment by drewvolz** [comment]
@hawkrives

**Comment by hawkrives** [comment]
I still haven't heard back from SARN.

**Comment by hawkrives** [comment]
okay fine, let's merge it. we can revert if they decide to go back to wix for some reason.

**Pull request merged**
