### PR TITLE
Android lists

### PR DESCRIPTION
**Pull request by hawkrives**
> New message
I'm breaking this up into smaller PRs, or "chapters":

- [x] (#541, #564) Preface, or: an AlphabetListView upgrade (to HEAD)
- [x] (#540) Introduction, or: how Touchable subsumed Touchable{Highlight,NativeFeedback,Opacity}
- [x] (#539) Chapter 1, or: the Creation of ListRow&co
- [x] (#538) Chapter 2, or: the Introduction of the Structural components (Row, Column, and List*)
- [x] (#562) Chapter 3.1, or: the Upkeep of Calendar
- [x] ~~(no pr) Chapter 3.2, or: the Maintenance of BusView~~ merged with #573 

---

- [x] ~~(no pr) Chapter 4.1, or: the Androidification of Calendar's list view~~ got merged into #572
- [x] (#571) Chapter 4.2, or: the Androidification of StudentOrgs' Detail view

---

- [x] (#570) Chapter 5.1, or: how to Port BuildingHours to Row+friends
- [x] (#572) Chapter 5.2, or: how to Port Calendar to Row+friends
- [x] (#566) Chapter 5.3, or: how to Port Dictionary to Row+friends
- [x] (#567) Chapter 5.4, or: how to Port Menus to Row+friends
- [x] (#569) Chapter 5.5, or: how to Port Courses to Row+friends
- [x] (#560) Chapter 5.6, or: how to Port News to Row+friends
- [x] (#565) Chapter 5.7, or: how to Port Orgs to Row+friends
- [x] (#573) Chapter 5.8, or: how to Port Transit/Bus to Row+friends

I will close this PR when all of the above are done.

---

> Old message

This PR brings Android up a lot closer to iOS in terms of feeling native.

~~I will include screenshots at a later date.~~

There are likely things that need tweaking. It's time to go difference hunting! If you don't like something in here, please speak up.

This PR centralizes some list styles so they're easier to update.

## iOS

Before | After
-------|------
calendar | calendar
dictionary | dictionary
hours | hours
menus | menus
news | news
org detail | org detail
org list | org list

## Android
Before | After
-------|------
calendar | calendar
dictionary | dictionary
hours | hours
menus | menus
news | news
org detail | org detail
org list | org list

### CODE REVIEW

**Comment by hawkrives** [comment]
I'm not terribly happy with the Menus look right now on Android. I'd love improvement suggestions there.

**Comment by hawkrives** [comment]
I appear to have accidentally removed the top/bottom border from the iOS list section headers. 

And I somehow removed the filter toolbar from iOS? Whoops.

**Comment by drewvolz** [comment]
Hah, where'd the filter bar go?

**Comment by hawkrives** [comment]
Update

## iOS

Before | After
-------|------
calendar | calendar
dictionary | dictionary
hours | hours
menus | menus
news | news
org detail | org detail
org list | org list
bus | bus



## Android
Before | After
-------|------
calendar | calendar
dictionary | dictionary
hours | hours
menus | menus
news | news
org detail | org detail
org list | org list
bus | bus

**Comment by hawkrives** [comment]
I'm still not sure where the iOS filters went – I'm not even touching that part of the code! – and I'm think the only reason the wrapping changed on GLOW is because I used a different simulator this time.

**Comment by hawkrives** [comment]
Found the iOS filters.

**Comment by hawkrives** [comment]
I will note that I'm looking for visual feedback in this PR, and not so much code?

I'll break up the different sections into PRs at a later date, and submit them separately - and slower than I have in the past.

**Comment by drewvolz** [comment]
You removed the disclosure indicator ' > ' from the iOS AlphabetListViews .. e.g. Student Orgs and Dictionary. Are you sure about that visual change? I see some benefit in saying "there's more content" with that little chevron.

**Comment by hawkrives** [comment]
> Note: iOS' default apps with an AlphabetListView thing, Contacts.app and Phone.app, both hide the chevrons.

I feel that having both the chevrons and the scrubber next to each other makes the view feel really "busy" on the right side, especially while scrolling.

**Comment by elijahverdoorn** [comment]
I really like this! @hawkrives has a feeling for styles that I'll never have.

A few notes:
* I don't think "proper" material design allows for the A-Z bar on the right side of the screen. Usually a dialog box pops up and shows the current letter . Like this: 

  android

* In 3-line lists, like the news view, the standard is to separate with a line for every element according to this spec: https://material.io/guidelines/components/lists.html#lists-specs
* Rather than just terminating the vertical line for the busses, can we have a line or arrow? It seems rather abrupt to just end it.

**Comment by hawkrives** [comment]
Thanks @elijahverdoorn!

1. Yeah, you're right… I'll keep that in mind and look for something in the future. For now, I'm going to declare that out-of-scope here.

2. Thanks! That's a handy page to have around, instead of me trying to infer rules from the Settings app…

3. I could … put a rounded end cap on the top/bottom, for Android? Or maybe just, like, hide the line segments that go past the dots on the extreme ends.

**Comment by hawkrives** [comment]
More links
- https://material.io/guidelines/components/subheaders.html
- https://material.io/guidelines/components/dividers.html#dividers-usage

@elijahverdoorn I'm conflicted about having three levels of elevation in the Menus view… do you have any Android-inspired ideas for a better way to present the filters? Should we maybe hide it behind a menu, or the Menu button?

**Comment by elijahverdoorn** [comment]
@hawkrives I've thought about this - let's do a floating action button! They're the most Android/Material Design ever, and they remove the 3 level problem. Maybe [this](https://github.com/mastermoo/react-native-action-button) component?

**Comment by hawkrives** [comment]
Can a FAB menu show static data? I'll admit that it's probably a good fit for Android. (I'm wondering where we would put the active filter count, if anywhere.)

How would it jive with these hypothetical future extensions? I think they could fit in the spin-off menu. 

- tap date to choose between days for the menu
- tap date to choose between meals within the day

I think we'll have to take the toolbar for Android for v2.1, though, unless one of your team wants to tackle it this week – my free coding has become rather suddenly restricted.

**Pull request closed without merging**
