### PR TITLE
Change bus name string comparison

### PR DESCRIPTION
**Pull request by drewvolz**
Change Express Line to Express Bus

### CODE REVIEW

**Comment by drewvolz** [comment]
The color was red when it should have been green.

**Red on green**
red
**Green on green**
green

**Comment by hawkrives** [comment]
Can you post an After screenshot, too, Drew?

**Comment by drewvolz** [comment]
Updated both before and after to make the change clear.

**Review by hawkrives — APPROVED** [review]
:shipit:

**Pull request merged**
