### PR TITLE
Move Event url extraction to ccc-server

### LINKED ISSUE #3019: iOS 9 SyntaxError
on startup: "RCTFatalException: Unhandled JS Exception: Unexpected token '.' (/var/containers/Bundle/Application/0AD4135D-47CA-4934-9EFC-020B5EE82433/AllAboutOlaf.app/main.jsbundle:411)"

### PR DESCRIPTION
**Pull request by hawkrives**
Depends on https://github.com/frog-pond/ccc-server/pull/82

Closes #3019 

Turns out the syntax error came from a line in `whatwg-url`, which I added in #2990 to fix get-urls@8 crashing because the URL didn't work right.

I have now removed get-urls entirely from our project, as well as the associated monkey-patching, because I cannot backfill `new.target` in such a way as to make whatwg-url work properly.

### CODE REVIEW

**Review by rye — APPROVED** [review]
Burn it all! 🔥

**Comment by hawkrives** [comment]
I have confirmed that this branch launches on iOS 9.

**Review by drewvolz — APPROVED** [review]
Confirmed as well.

**Comment by rye** [comment]
Merging.

**Pull request merged**
