### PR TITLE
Move the Bookstore into the Post Office section

### PR DESCRIPTION
**Pull request by hawkrives**
I don't think the "convenience store" really exists as a distinct entity any longer.

### CODE REVIEW

**Review by rye — CHANGES_REQUESTED** [review]
I'm fine with merging the Convenience Store and the Bookstore together, but I think they are independent of the Post Office + Print Center.

**Comment by hawkrives** [comment]
@rye I don't like one-item sections, which is why I merged them.

I would appreciate suggestions towards how best to combine or reorganize them.

**Comment by drewvolz** [comment]
I think the suggestion is how not to do something; I think we would all prefer to not combine the Post Office and Bookstore, as per the out-of-band discussion.

**Comment by hawkrives** [comment]
> I think we would all prefer to not combine the Post Office and Bookstore, as per the out-of-band discussion.

No, that is incorrect - I wish to combine the two sections, so as to avoid a 1-item section.

**Comment by rye** [comment]
N.B.: We have a `Museum` section with one item in it already.

Is it possible to have a title-less section?

I would be fine with merging the now-three places under `Mail, Packages, Printing, and Books` or something like that.

**Pull request closed without merging**
