### PR TITLE
Course row view cleanup

### LINKED ISSUE #2961: Course notes are lengthy on list rows
Also stemming from #2952, course list notes were added to the list rows. They can get kind of lengthy. 

> I want to either remove them from the list rows, or limit them to 1 line.

<details>
<summary>Screenshots of long course notes</summary>

~ | ~
--|--
telegram-cloud-file-3-831937890-90711-7770742396837060420 | telegram-cloud-file-3-830932384-97183-1821923187031404446
telegram-cloud-file-3-830932499-97272--4431890308569011349
</summary>

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #2961 

Use row and detail to cleanup the course search rows

### CODE REVIEW

**Review by rye — DISMISSED** [review]

**Comment by hannesmcman** [comment]
@drewvolz screenshots?

**Review by hawkrives — DISMISSED** [review]
Isn't Detail a block level element? Can't you just use it instead of wrapping each one in a Row?

**Comment by hawkrives** [comment]
Do we still need the negative margin on the Detail elements that used to be on the Rows?

**Comment by drewvolz** [comment]
Yeah. This is undoing the positive margin which the `Detail` component adds in order to match what a normal `Text` component does.

**Comment by hawkrives** [comment]
ah, I didn't see it still being applied.

**Comment by hawkrives** [comment]
I'll second @hannesmcman - screenshots :-D?

**Comment by drewvolz** [comment]
<details>
<summary> Screenshots </summary>

Platform | Before | After
--|--|--
Android | android-before |  android-after
iOS | before-ios | after-ios

</details>

**Review by hawkrives — APPROVED** [review]
Sure

**Pull request merged**
