### PR TITLE
Greenkeeper/eslint plugin react 7.5.1

### PR DESCRIPTION
**Pull request by hawkrives**
includes a crash fix

### CODE REVIEW

**Comment by hawkrives** [comment]
Poll: Does anyone want the `jsx-sort-props` rule to be enabled, or can I just turn it off?

/cc @drewvolz, @rye, @elijahverdoorn

**Comment by rye** [comment]
Hum. It'd be nice if the props were sorted alphabetically, but for now we can turn the grumbling off.

**Comment by hawkrives** [comment]
If you'd like us to enable it, I guess file an issue like https://github.com/StoDevX/AAO-React-Native/issues/1936? I'll turn it off for this PR.

**Comment by hawkrives** [comment]
Well. I'll actually file an issue; that rule has been enabled for a very long time, and I don't see why we shouldn't enable it.

**Pull request merged**
