### PR TITLE
Release v2.8.0, beta 8

### PR DESCRIPTION
**Pull request by rye**
View [the comparison from v2.7.0](https://github.com/StoDevX/AAO-React-Native/compare/v2.7.0...release/v2.8.0-beta.8).

## Checklist
- [x] Branch pushed
- [x] Signed-off/approved
- [x] Tag pushed
- [x] [GitHub release][release] created to target pushed tag
- [x] Release PR [successfully builds][t-pr] against `master`
- [x] GitHub Wiki [release notes updated][wiki]
- [ ] Tag build passes ([js][t-js], [ios][t-ios], [android][t-android])
  - [x] Android deployed.
  - [ ] iOS **not** deployed. :warning: 
- [x] Release PR merged to `master`.

[release]: https://github.com/StoDevX/AAO-React-Native
[pr]: https://github.com/StoDevX/AAO-React-Native/pull/5105
[wiki]: https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes#v280
[t-pr]: https://github.com/StoDevX/AAO-React-Native/actions/runs/736179794
[t-js]: https://github.com/StoDevX/AAO-React-Native/runs/2313258168
[t-android]: https://github.com/StoDevX/AAO-React-Native/runs/2313258144
[t-ios]: https://github.com/StoDevX/AAO-React-Native/runs/2313258195

### CODE REVIEW

**Comment by hawkrives** [comment]
Oops. 

image

**Review by hawkrives — APPROVED** [review]

**Comment by rye** [comment]
iOS release build still not so happy. Everything else looks good on the sourcemap front, though!

Screenshot from 2021-04-10 10-40-46

**Comment by rye** [comment]
Turns out that the failing tag build means I can't merge this PR, either. @hawkrives what do you think—is it possible to get the privacy policy stuff acknowledged? I think we can follow up with another beta PR.

**Comment by hawkrives** [comment]
I think I've signed everything now…

**Comment by hawkrives** [comment]
I can't find a Privacy Statement, though… not sure if I actually got everything.

**Pull request merged**
