### PR TITLE
Upgrade to React Native 0.50 / Flow 0.56

### PR DESCRIPTION
**Pull request by hawkrives**
**WIP!**

To do:

- [x] Actually run the app and see what's broken
- [x] Fix home screen reducer test(?) (https://github.com/StoDevX/AAO-React-Native/pull/1840#issuecomment-342716180)
- [x] Make bus tests always run in UTC
- [x] Update bus route schema for new properties
- [x] Fix react-native internal flow error
- [x] "Fix" react-navigation flow errors
- [x] "Fix" `this.props.navigation` flow errors
- [x] Fix FilterType flow errors
- [x] Make codeclimate ignore /flow-typed
- [ ] There's a dark line at the bottom of our toolbar now
- [ ] "Error: the `<Image>` component cannot contain children. If you want to render content on top of the image, consider using absolute positioning." (https://github.com/facebook/react-native/commit/c55fae1e2697520a55d23a0816552bec09920142)
- [x] StatusBar doesn't go back to white text after closing SFViewController
- [x] Transportation "null is not an object (evaluating _state.schedule)"
- [x] make busview look good (https://github.com/StoDevX/AAO-React-Native/pull/1879)

---

~~Some of the bus tests are failing for some reason.~~

~~I still need to update the schema for the bus routes to accommodate the added keys.~~

~~That pretty much gets us running again. Then I need to actually launch the app and test it, because I revamped both the bus line views and the types around all the redux stores.~~

~~I should be able to do the bus refactoring on master, so I’ll want to extract that from this PR.~~

~~I should be able to do the new redux types on master, so I’ll try to pull that out as well.~~

That should leave the main changes in a future react-native@0.50 PR as going from `React.Component<DefaultProps, Props, State>` to `React.Component<Props, State>`, which is pretty much just mechanical and should be a much smaller diff. 

I should also pull out some of the other type fixes I made (eg, turns out that `_.head` wants an array, not a string, but we keep giving it strings, so I switched to `str[0]`). 

---

## Eventual PRs

- [x] Bus view refactoring (https://github.com/StoDevX/AAO-React-Native/pull/1879)
- [x] Typed Redux stores (https://github.com/StoDevX/AAO-React-Native/pull/1880)
- [x] Misc. fixes
- [ ] React-Native 0.50 / Flow 0.56 (+codeclimate) / flow typedefs for a bunch of dependencies
- [x] Remove react-native-view-shot
- [x] Remove SIS/courses tab
- [x] Remove unused packages (`marked`, `react-addons-shallow-compare`)

---
<details><summary><code>git diff --stat master</code></summary>

```
 .codeclimate.yml                                   |    1 +
 .flowconfig                                        |   30 +-
 android/app/build.gradle                           |    1 +
 .../java/com/allaboutolaf/MainApplication.java     |    5 +
 dangerfile.js                                      |   18 +-
 data/_schemas/bus-times.yaml                       |   14 +-
 data/bus-times/blue-line.yaml                      |   25 +-
 data/bus-times/express.yaml                        |   75 +-
 data/bus-times/red-line.yaml                       |    4 +
 flow-typed/.eslintrc.yaml                          |    5 +
 .../react-native-alphabetlistview_v1.x.x.js        |   39 +
 .../react-native-sortable-list_v1.x.x.js           |   36 +
 flow-typed/npm/babel-eslint_vx.x.x.js              |   18 -
 flow-typed/npm/babel-preset-react-native_vx.x.x.js |   18 -
 flow-typed/npm/buffer_vx.x.x.js                    |   18 -
 flow-typed/npm/css-select_v1.x.x.js                |  204 +
 flow-typed/npm/css-select_vx.x.x.js                |   18 -
 flow-typed/npm/delay_v2.x.x.js                     |   12 +
 flow-typed/npm/delay_vx.x.x.js                     |   18 -
 flow-typed/npm/eslint-plugin-babel_vx.x.x.js       |   18 -
 flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js    |   18 -
 flow-typed/npm/eslint-plugin-react_vx.x.x.js       |   18 -
 flow-typed/npm/eslint_vx.x.x.js                    |   18 -
 flow-typed/npm/events_vx.x.x.js                    |   18 -
 flow-typed/npm/get-urls_v7.x.x.js                  |   19 +
 flow-typed/npm/html-entities_v1.x.x.js             |   18 +
 flow-typed/npm/html-entities_vx.x.x.js             |   18 -
 flow-typed/npm/htmlparser2_vx.x.x.js               |   18 -
 flow-typed/npm/jest-react-native_vx.x.x.js         |   18 -
 .../npm/{jest_v18.x.x.js => jest_v21.x.x.js}       |  252 +-
 flow-typed/npm/junk_v2.x.x.js                      |    8 +
 flow-typed/npm/lodash_v4.x.x.js                    | 4093 +++++++++++++++++++-
 flow-typed/npm/minimist_v1.x.x.js                  |   31 +
 flow-typed/npm/moment-timezone_v0.5.x.js           |    8 +
 flow-typed/npm/moment-timezone_vx.x.x.js           |   18 -
 flow-typed/npm/moment_v2.3.x.js                    |  327 ++
 flow-typed/npm/moment_v2.x.x.js                    |  236 --
 flow-typed/npm/pify_v3.x.x.js                      |   22 +
 flow-typed/npm/prop-types_v15.x.x.js               |   34 +
 flow-typed/npm/querystring_vx.x.x.js               |   18 -
 flow-typed/npm/react-markdown_vx.x.x.js            |    6 +
 .../npm/react-native-alphabetlistview_vx.x.x.js    |   18 -
 flow-typed/npm/react-native-button_v2.x.x.js       |   20 +
 flow-typed/npm/react-native-button_vx.x.x.js       |   18 -
 .../npm/react-native-calendar-events_v1.x.x.js     |  132 +
 .../npm/react-native-communications_v2.x.x.js      |   11 +
 .../npm/react-native-communications_vx.x.x.js      |   18 -
 flow-typed/npm/react-native-custom-tabs_vx.x.x.js  |    6 +
 flow-typed/npm/react-native-device-info_vx.x.x.js  |   18 -
 .../react-native-google-analytics-bridge_vx.x.x.js |    6 +
 flow-typed/npm/react-native-keychain_vx.x.x.js     |   16 +-
 .../npm/react-native-linear-gradient_v2.1.0.js     |   26 -
 .../npm/react-native-linear-gradient_v2.x.x.js     |   22 +
 flow-typed/npm/react-native-maps_vx.x.x.js         |    6 +
 flow-typed/npm/react-native-network-info_vx.x.x.js |    6 +
 flow-typed/npm/react-native-onesignal_vx.x.x.js    |   18 -
 .../npm/react-native-parallax-view_vx.x.x.js       |   18 -
 flow-typed/npm/react-native-restart_v0.0.x.js      |    8 +
 flow-typed/npm/react-native-safari-view_v2.x.x.js  |   23 +
 flow-typed/npm/react-native-search-bar_vx.x.x.js   |    6 +
 .../npm/react-native-sortable-list_vx.x.x.js       |   18 -
 .../npm/react-native-tableview-simple_v0.x.x.js    |  114 +-
 flow-typed/npm/react-native-vector-icons_vx.x.x.js |   28 +-
 ...l-jest_vx.x.x.js => react-navigation_vx.x.x.js} |    8 +-
 flow-typed/npm/react-redux_v5.x.x.js               |  132 +
 flow-typed/npm/react-redux_vx.x.x.js               |   18 -
 flow-typed/npm/react-test-renderer_vx.x.x.js       |   18 -
 flow-typed/npm/redux-logger_vx.x.x.js              |   18 -
 flow-typed/npm/redux-promise_vx.x.x.js             |   18 -
 flow-typed/npm/redux-thunk_vx.x.x.js               |   18 -
 flow-typed/npm/redux_v3.x.x.js                     |  113 +-
 flow-typed/npm/stream_vx.x.x.js                    |   18 -
 flow-typed/npm/string-natural-compare_v2.x.x.js    |   10 +
 flow-typed/npm/timers_vx.x.x.js                    |   18 -
 flow-typed/npm/titlecase_v1.x.x.js                 |    8 +
 flow-typed/npm/titlecase_vx.x.x.js                 |   18 -
 flow-typed/npm/xml2js_vx.x.x.js                    |   16 +-
 index.ios.js                                       |    1 -
 index.android.js => index.js                       |    0
 ios/AllAboutOlaf.xcodeproj/project.pbxproj         |  471 ++-
 ios/AllAboutOlaf/AppDelegate.m                     |    2 +-
 package.json                                       |   16 +-
 source/app.js                                      |    9 +-
 source/flux/index.js                               |   55 +-
 source/flux/init.js                                |   47 +-
 source/flux/parts/app.js                           |   54 +-
 source/flux/parts/homescreen.js                    |   55 +-
 source/flux/parts/menus.js                         |   35 +-
 source/flux/parts/settings.js                      |  222 +-
 source/flux/parts/sis.js                           |  162 +-
 source/lib/financials/index.js                     |    1 +
 source/lib/storage.js                              |   31 +-
 source/navigation.js                               |    2 +-
 source/views/building-hours/detail/badge.js        |    4 +-
 source/views/building-hours/detail/building.js     |    2 +-
 source/views/building-hours/detail/header.js       |    4 +-
 source/views/building-hours/detail/index.js        |   14 +-
 .../building-hours/detail/schedule-row.android.js  |   12 +-
 .../building-hours/detail/schedule-row.ios.js      |   12 +-
 .../detail/schedule-table.android.js               |   12 +-
 .../building-hours/detail/schedule-table.ios.js    |   12 +-
 .../lib/__tests__/parse-hours.test.js              |    4 +-
 source/views/building-hours/list.js                |   14 +-
 source/views/building-hours/report/editor.js       |   74 +-
 source/views/building-hours/report/overview.js     |   70 +-
 source/views/building-hours/row.js                 |    3 +-
 source/views/building-hours/stateful-list.js       |   24 +-
 source/views/building-hours/types.js               |    8 +-
 source/views/calendar/calendar-google.js           |   22 +-
 source/views/calendar/event-detail.android.js      |   27 +-
 source/views/calendar/event-detail.ios.js          |   28 +-
 source/views/calendar/event-list.js                |   16 +-
 source/views/calendar/event-row.js                 |   10 +-
 .../__tests__/__snapshots__/notice.test.js.snap    |    3 -
 source/views/components/__tests__/open-url.test.js |    2 +
 source/views/components/cells/textfield.js         |   30 +-
 .../{android.js => datepicker.android.js}          |    2 +-
 .../datepicker/{ios.js => datepicker.ios.js}       |   15 +-
 source/views/components/datepicker/index.js        |   53 +-
 .../filter/__tests__/apply-filter.test.js          |    1 -
 source/views/components/filter/apply-filters.js    |    3 +-
 source/views/components/filter/filter-view.js      |   33 +-
 source/views/components/filter/types.js            |   95 +-
 source/views/components/html-view.js               |   13 +-
 source/views/components/list/list-empty.js         |    8 +-
 source/views/components/list/list-footer.js        |   10 +-
 source/views/components/markdown/code.js           |    4 +-
 source/views/components/markdown/index.js          |   23 +-
 source/views/components/markdown/link.js           |   18 +-
 source/views/components/markdown/list.js           |   10 +-
 source/views/components/markdown/selectable.js     |    4 +-
 source/views/components/nav-buttons/share.js       |    8 +-
 source/views/components/open-url.js                |   31 +-
 .../components/searchable-alphabet-listview.js     |    6 +-
 source/views/contacts/contact-detail.js            |    6 +-
 source/views/contacts/contact-list.js              |    4 +-
 source/views/contacts/contact-row.js               |   10 +-
 source/views/dictionary/detail.js                  |   10 +-
 source/views/dictionary/list.js                    |    7 +-
 source/views/faqs/index.js                         |   12 +-
 source/views/help/index.js                         |    4 +-
 source/views/help/wifi.js                          |    9 +-
 source/views/home/edit/list.android.js             |    2 +-
 source/views/home/edit/list.ios.js                 |    2 +-
 source/views/home/edit/row.android.js              |    2 +-
 source/views/home/edit/row.ios.js                  |    2 +-
 source/views/home/home.js                          |   22 +-
 source/views/menus/carleton-menus.js               |    4 +-
 source/views/menus/components/dietary-tags.js      |    4 +-
 source/views/menus/components/fancy-menu.js        |   52 +-
 source/views/menus/dev-bonapp-picker.js            |   16 +-
 source/views/menus/lib/choose-meal.js              |   14 +-
 source/views/menus/menu-bonapp.js                  |    4 +-
 source/views/menus/menu-github.js                  |   34 +-
 source/views/news/fetch-feed.js                    |    4 +-
 source/views/news/news-container.js                |   42 +-
 source/views/news/news-list.js                     |   18 +-
 source/views/news/news-row.js                      |   12 +-
 source/views/settings/credits.js                   |    1 +
 source/views/settings/legal.js                     |    4 +-
 source/views/settings/privacy.js                   |    4 +-
 .../views/settings/sections/login-credentials.js   |   29 +-
 source/views/settings/sections/odds-and-ends.js    |   20 +-
 source/views/settings/sections/support.js          |    8 +-
 source/views/sis/balances.js                       |   46 +-
 source/views/sis/student-work/detail.android.js    |   45 +-
 source/views/sis/student-work/detail.ios.js        |   47 +-
 source/views/sis/student-work/index.js             |   22 +-
 source/views/sis/student-work/job-row.js           |   10 +-
 source/views/streaming/radio.js                    |    6 +-
 source/views/streaming/streams/list.js             |   20 +-
 source/views/streaming/streams/row.js              |    4 +-
 source/views/streaming/webcams.js                  |    4 +-
 source/views/student-orgs/detail.android.js        |   10 +-
 source/views/student-orgs/detail.ios.js            |   10 +-
 source/views/student-orgs/list.js                  |   26 +-
 source/views/transportation/bus/bus-line.js        |  267 +-
 source/views/transportation/bus/bus-stop-row.js    |  106 +-
 source/views/transportation/bus/bus-view.js        |   69 +-
 .../bus/components/progress-chunk.js               |   22 +-
 .../__tests__/get-current-bus-iteration.test.js    |   65 +
 .../bus/lib/__tests__/get-schedule-for-now.test.js |   50 +-
 .../lib/__tests__/get-set-of-stops-for-now.test.js |   71 -
 .../bus/lib/__tests__/make-subtitle.test.js        |   52 +
 .../bus/lib/__tests__/moment.helper.js             |    8 +
 .../bus/lib/__tests__/parse-time.test.js           |   17 +
 .../bus/lib/__tests__/process-bus-line.test.js     |   33 +
 .../bus/lib/get-current-bus-iteration.js           |   37 +
 .../transportation/bus/lib/get-schedule-for-now.js |   41 +-
 .../bus/lib/get-set-of-stops-for-now.js            |   38 -
 source/views/transportation/bus/lib/index.js       |    5 +-
 .../views/transportation/bus/lib/make-subtitle.js  |   41 +
 source/views/transportation/bus/lib/parse-time.js  |   20 +
 .../transportation/bus/lib/process-bus-line.js     |   49 +
 source/views/transportation/bus/map.js             |   83 +-
 source/views/transportation/bus/types.js           |   54 +-
 source/views/transportation/other-modes/detail.js  |    6 +-
 source/views/transportation/other-modes/list.js    |    4 +-
 source/views/transportation/other-modes/row.js     |   10 +-
 source/views/transportation/types.js               |    1 +
 yarn.lock                                          |  563 +--
 201 files changed, 7840 insertions(+), 3171 deletions(-)
```
</details>

### CODE REVIEW

**Comment by hawkrives** [comment]
Next up: 

```
Error: source/views/student-orgs/list.js:177
177:     this.props.navigation.navigate('StudentOrgsDetailView', {org: data})
         ^^^^^^^^^^^^^^^^^^^^^ type application of type `NavigationScreenProp`. Too many type arguments. Expected at most 1
447: export type NavigationScreenProp<S: {}> = {
                                      ^^^^^ See type parameters of definition here. See: node_modules/react-navigation/src/TypeDefinition.js:447
```

(about 20 errors)

Also, for some reason Flow isn't distinguishing between the types of filters (Picker, List, Toggle):

```
Error: source/views/menus/lib/choose-meal.js:13
                                              v------------
 13:   const mealChooserFilter: ?PickerType = filters.find(
 14:     f => f.type === 'picker' && f.spec.title === "Today's Menus",
 15:   )
       ^ object type. This type is incompatible with
 13:   const mealChooserFilter: ?PickerType = filters.find(
                                 ^^^^^^^^^^ object type
  Property `spec` is incompatible:
     18:   +spec: ToggleSpecType,
                  ^^^^^^^^^^^^^^ object type. This type is incompatible with. See: source/views/components/filter/types.js:18
     62:   +spec: PickerSpecType,
                  ^^^^^^^^^^^^^^ object type. See: source/views/components/filter/types.js:62
      Property `selected` is incompatible:
         62:   +spec: PickerSpecType,
                      ^^^^^^^^^^^^^^ property `selected`. Property not found in. See: source/views/components/filter/types.js:62
         18:   +spec: ToggleSpecType,
                      ^^^^^^^^^^^^^^ object type. See: source/views/components/filter/types.js:18
```

(about 20 errors)

Furthermore, this one's inside React-Native:

```
Error: node_modules/react-native/local-cli/core/index.js:111
111:     ? Config.load(path.resolve(__dirname, cliArgs.config))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ rest parameter array of call of method `resolve`. Has some incompatible type argument with
1314:   declare function resolve(...parts: Array<string>): string;
                                           ^^^^^^^^^^^^^ array type. See lib: /private/tmp/flow/flowlib_5806877/node.js:1314
  Type argument `T` is incompatible:
    111:     ? Config.load(path.resolve(__dirname, cliArgs.config))
                                                   ^^^^^^^^^^^^^^ boolean. This type is incompatible with
    1314:   declare function resolve(...parts: Array<string>): string;
                                                     ^^^^^^ string. See lib: /private/tmp/flow/flowlib_5806877/node.js:1314
```

Then, we've got a new set of react-navigation errors:

```
Error: node_modules/react-navigation/src/navigators/DrawerNavigator.js:89
         v----------
 89:     <DrawerView
 90:       {...props}
 91:       drawerBackgroundColor={drawerBackgroundColor}
...:
 98:     />
         -^ React element `DrawerView`
 50:     NavigationState,
         ^^^^^^^^^^^^^^^ object type. This type is incompatible with. See: node_modules/react-navigation/src/views/Drawer/DrawerView.js:50
 37:       InjectedProps<S, A, O> & NavigationNavigatorProps<O, S>
                         ^ empty. See: node_modules/react-navigation/src/navigators/createNavigator.js:37
```

I think that's all of the Flow errors that we've got left. (91 errors.)

**Comment by hawkrives** [comment]
oh my god codeclimate

> codeclimate — 660 issues to fix

**Comment by hawkrives** [comment]
This is by far the worst react-native upgrade I've gone through. So many flow changes.

**Comment by hawkrives** [comment]
@rye How do I stop code climate from looking at the /flow-typed folder?

**Comment by hawkrives** [comment]
Alright, I'm down to one flow error!

```
Error: node_modules/react-native/local-cli/core/index.js:111
111:     ? Config.load(path.resolve(__dirname, cliArgs.config))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ rest parameter array of call of method `resolve`. Has some incompatible type argument with
1314:   declare function resolve(...parts: Array<string>): string;
                                           ^^^^^^^^^^^^^ array type. See lib: /tmp/flow/flowlib_3f03ece2/node.js:1314
  Type argument `T` is incompatible:
    111:     ? Config.load(path.resolve(__dirname, cliArgs.config))
                                                   ^^^^^^^^^^^^^^ boolean. This type is incompatible with
    1314:   declare function resolve(...parts: Array<string>): string;
                                                     ^^^^^^ string. See lib: /tmp/flow/flowlib_3f03ece2/node.js:1314


Found 1 error
```

**Comment by rye** [comment]
@hawkrives, I just turned off `flow-typed/` in the CodeClimate YAML file via ec0afaba4aa5c37e36e7a5bd965cd7b925d5d320.  Is it possible for you to remove your override so we get true results?  If not, that's fine, the issues will show up again later on.

**Comment by hawkrives** [comment]
@rye I have no idea. I’ll try later.

**Comment by hawkrives** [comment]
```
FAIL source/flux/__tests__/update-view-order.test.js
  ● Test suite failed to run
    Reducer "homescreen" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. If you don't want to set a value for this reducer, you can use null instead of undefined.
      
      at node_modules/redux/lib/combineReducers.js:56:13
          at Array.forEach (<anonymous>)
      at assertReducerShape (node_modules/redux/lib/combineReducers.js:51:25)
      at combineReducers (node_modules/redux/lib/combineReducers.js:107:5)
      at Object.<anonymous> (source/flux/index.js:25:69)
      at Object.<anonymous> (source/views/components/filter/filter-view.js:37:172)
```

**Comment by hawkrives** [comment]
screen shot 2017-11-08 at 11 09 59 am

**Comment by hawkrives** [comment]
Superseded by #1888 / #1892.

**Pull request closed without merging**
