### PR TITLE
Refactor some stuff around login

### PR DESCRIPTION
**Pull request by hawkrives**
this doesn't fix the login issue.

but it's a collection of other refactorings that I want to do in here.

including moving the login status into a new reducer – `state.login.status`.

### CODE REVIEW

**Comment by drewvolz** [comment]
I really like the extraction of login status to its own reducer 👍

**Comment by hawkrives** [comment]
@rye Could you test this in the simulator, please? It randomly started working for me yesterday, and I'm curious what results you will get.

**Comment by rye** [comment]
Yeah, I'll try and build this PR when I get back later tonight. I'll review then.

**Review by rye — APPROVED** [review]
DRSLGTM

**Pull request merged**
