### PR TITLE
Add exception for KSTO on iOS

### LINKED ISSUE #156: Add exception for KSTO website to Info.plist
Otherwise ATS blocks it.

### PR DESCRIPTION
**Pull request by elijahverdoorn**
I've never done this before, thought that I should take a crack at it. Let me know if there is something that I've messed up.

Closes #156.

### CODE REVIEW

**Comment by hawkrives** [comment]
Only that we don't let Xcode edit that file… look at that diff.

**Comment by hawkrives** [comment]
I always edit it in Sublime because of that.

**Comment by hawkrives** [comment]
Actually.

I didn't realize that KSTO was on pages.stolaf.

Everything there also runs over HTTPS, so all we need to do it change the link to `https://pages.stolaf.edu/ksto/listen/` and it'll work.

**Comment by elijahverdoorn** [comment]
Funny, it didn't look like that when I ran `git diff`. It only showed a few lines different. Can we keep it or should I revert and add the diff?

**Comment by hawkrives** [comment]
Did it look like https://github.com/StoDevX/AAO-React-Native/pull/159/files?w=0 ?

**Comment by hawkrives** [comment]
I'd prefer to switch to loading over HTTPS, since that's doesn't require the exception.

If we do continue with the exception, we should switch to `NSTemporaryExceptionAllowsInsecureHTTPLoads` instead of `NSThirdPartyExceptionAllowsInsecureHTTPLoads`, since "we" control that domain.

**Comment by elijahverdoorn** [comment]
@hawkrives It did look like that, yeah.

**Comment by hawkrives** [comment]
Xcode has a habit of rearranging that file, in addition to editing the whitespace. I think there's a PR in here somewhere where Drew's copy, like, flipped everything.

Why? Because Xcode.

**Comment by elijahverdoorn** [comment]
I'd rather switch to HTTPS. Closing this PR and opening another for that soon.

**Comment by hawkrives** [comment]
Kk

**Pull request closed without merging**
