### PR TITLE
Switch Prettier to using tabs instead of spaces 😈

### PR DESCRIPTION
**Pull request by rye**
Prettier supports this now, and I like tabs more.  As long as Prettier is managing the indentation, (which it is) we should be fine.

### CODE REVIEW

**Comment by hawkrives** [comment]
Whitespace diff: https://github.com/StoDevX/AAO-React-Native/pull/2153/files?w=1

**Comment by hawkrives** [comment]
@rye that's a bit big

**Comment by rye** [comment]
Would you rather one PR for each file? 😉

**Review by hawkrives — DISMISSED** [review]

**Comment by drewvolz** [comment]
Does this bump your contributor status waaaay up??

**Review by drewvolz — DISMISSED** [review]

**Comment by rye** [comment]
Hehehe yeah it does.

**Comment by hawkrives** [comment]
That's his real goal…

**Comment by rye** [comment]
I mean, you're not wrong, but also tabs are probably better and it doesn't matter since prettier is the source of truth.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
