### PR TITLE
add segmented control dependency from react-native-community

### PR DESCRIPTION
**Pull request by drewvolz**
Fixes a warning in the app regarding `SegmentedControlIOS`

> `SegmentedControlIOS` has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from `@react-native-community/segmented-control` instead of `react-native`.

### CODE REVIEW

**Comment by drewvolz** [comment]
Do we know why `build for iOS` and ` build for android` jobs were skipped?

**Comment by hawkrives** [comment]
Looks like they depend on tsc passing…

**Comment by drewvolz** [comment]
@hawkrives @rye until we fix all of the tsc errors, should we adjust the pipeline to not skip the native builds?

**Comment by hawkrives** [comment]
Yeah

**Review by rye — APPROVED** [review]

**Comment by drewvolz** [comment]
[Error when running detox](https://github.com/StoDevX/AAO-React-Native/actions/runs/3509543699/jobs/5878767707#step:15:1)

```
import { device } from 'detox';

SyntaxError: Cannot use import statement outside a module
```

I think we need to configure a transform exception for detox (or something else) similarly to how we fixed this type of module error before for `@frogpond` and `@react-native` scoped packages e.g. https://github.com/StoDevX/AAO-React-Native/pull/6152/commits/1ff97cf3e106e98656ec88a2a071487f9b877e32

**Pull request merged**
