### PR TITLE
nix duplicate titles in descriptions

### PR DESCRIPTION
**Pull request by drewvolz**
removes redundant dietary icon titles in the description texts

### CODE REVIEW

**Review by hawkrives — CHANGES_REQUESTED** [review]
You missed MWGCI :(

**Comment by drewvolz** [comment]
Thanks.

**Review by hawkrives — CHANGES_REQUESTED** [review]
Missed Vegetarian too. I think all the others are covered.

**Comment by drewvolz** [comment]
Agh. I'll get it. Thanks, sorry.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
