### PR TITLE
Add "Hours may change without notice" footer to Building Hours

### PR DESCRIPTION
**Pull request by hawkrives**
Closes https://github.com/StoDevX/AAO-React-Native/issues/1517
Depends on #1544

> Building hours subject to change without notice
> Data collected by the humans of All About Olaf

List | Detail
--- | ---
screen shot 2017-09-10 at 3 35 53 pm | screen shot 2017-09-10 at 3 35 58 pm

### CODE REVIEW

**Comment by hawkrives** [comment]
reopening PR to rebuild with #1544 included

**Review by rye — COMMENTED** [review]
See https://github.com/StoDevX/AAO-React-Native/pull/1543#issuecomment-328516406 — I'd approve but there might be some style change to make it look better.

**Review by elijahverdoorn — APPROVED** [review]
It's not perfect (@rye has a point), but it's an improvement.

**Comment by hawkrives** [comment]
@rye / @elijahverdoorn So is this "I want to change the styles first, then merge" or is it "merge, then we can tweak the styles"?

**Comment by rye** [comment]
@hawkrives Frankly I'd be okay with seeing this PR in production; (merge, then tweak later) it meets the (undefined but inferrable) acceptance criteria for #1517.

**Comment by elijahverdoorn** [comment]
Merge in now, if either @rye or myself want to tweak it, that's on us to do in a future PR.

**Pull request merged**
