### PR TITLE
update the appearance and copy of the hours editor

### PR DESCRIPTION
**Pull request by drewvolz**
Before | After
--|--
ios before | ios after
android before |  android after

### CODE REVIEW

**Comment by drewvolz** [comment]
I can try to:
- [x] Split up android and iOS styles. The new android view doesn't look improved to me yet, it looks worse than before.
- [x] Improve the padding on the iOS week checkboxes so that they match the padding of the rows below

**Comment by hawkrives** [comment]
I like both of your suggestions.

I also think that the iOS one looks a lot better already!

**Comment by hawkrives** [comment]
@drewvolz This is what Google does in Maps:

**Comment by hawkrives** [comment]
… so we could potentially mimic the iOS buttons (with a different color?) for Android. I think it's OK if the Open/Close remain on different rows.

**Comment by drewvolz** [comment]
Gave it another go and updated the screenshots.

[Updated diff without whitespace](https://github.com/StoDevX/AAO-React-Native/pull/5948/files?diff=split&w=1)

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
