### PR TITLE
disable facilities and helpdesk tools

### PR DESCRIPTION
**Pull request by hawkrives**
At least until we actually ask them if they want in.

### CODE REVIEW

**Comment by drewvolz** [comment]
I’d hesitate on advertising it as much as we’re doing in the release notes if it ships as disabled.

...and hidden.

**Comment by drewvolz** [comment]
Actually, what is the harm in enabling / making these available? They're no different than heading directly to the Facilities WO form itself, and no different than opening an email to the helpdesk yourself.

**Comment by drewvolz** [comment]
My concerns are with the subject line in the helpdesk email template.

>  subject: I Haz A Problem
>  body:  [...] Please include your name, phone number, and next of kin.

All jokes aside, if we want to ship this, it should probably be presented with a blank subject and blank body. Filling in the "to" field is fine as it saves someone from having to do that. But the user will have to first delete the subject and body, unlike a blank email. The template does more harm than good here, IMHO.

**Comment by hawkrives** [comment]
I would like to check with Heather on the wording of the HelpDesk card, and with Facilities to make sure they're OK with exposing the form to a wider audience.

**Comment by hawkrives** [comment]
AFAIK, we aren't advertising either of these tools in the release notes.

**Comment by drewvolz** [comment]
Just checked. You are correct.

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
