### PR TITLE
Fix webcam schema

### PR DESCRIPTION
**Pull request by drewvolz**
@hawkrives' fix to the webcams schema

### CODE REVIEW

**Comment by hawkrives** [comment]
Sigh.

**Comment by hawkrives** [comment]
I think the next step is to add debugging to `scripts/validate-data` to figure out WTF is going on inside it.

The iteration logic is all before the `// MARK: Helpers` comment.

Let's see what my first attempt at debugging shows us: 916bbf4

**Comment by drewvolz** [comment]
`cat ./data/_schemas/webcams.yaml` produced:

```yaml
$schema: http://json-schema.org/draft-04/schema#

additionalProperties: false
required: [name, pageUrl, streamUrl, thumbnail, tagline, accentColor]
properties:
  name: {type: string}
  pageUrl: {type: string, format: uri}
  streamUrl: {type: string, format: uri}
  thumbnail: {type: string}
  tagline: {type: string}
  accentColor:
    type: array
    items: [{type: number}, {type: number}, {type: number}]
    additionalItems: false

```

and the error it spat out was:

`webcams/0-alumni-hall-west.yaml is invalid`
```json
{
  "keyword": "required",
  "dataPath": "",
  "schemaPath": "#/required",
  "params": {
    "missingProperty": ".url"
  },
  "message": "should have required property '.url'"
}
```

**Comment by hawkrives** [comment]
So it didn't actually run my edited code?

**Comment by hawkrives** [comment]
It should have printed out `file, {schema}` lines for each file, before deciding if it was invalid or not.

**Comment by hawkrives** [comment]
master checks: [name, url]
the branch checks: [name, other stuff]

Travis ran Prettier, which does the git stuff

I think that the git stuff is not putting us back on the commit that we started on

So if I `cat` the schema again, right before the validator runs, it'll be the copy from master

let's go test that theory

**Comment by hawkrives** [comment]
Yeah, the git stuff is borkeden. I fix ish ing.

**Review by hawkrives — APPROVED** [review]
woot

**Pull request merged**
