### PR TITLE
Nativify android calendar detail

### PR DESCRIPTION
**Pull request by drewvolz**
This PR brings the calendar detail view for android into line with platform styles.

Before | After
---|---
screen shot 2017-06-18 at 3 02 30 pm | screen shot 2017-06-18 at 3 01 33 pm

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]
Sure, but after this I want us to look at making the iOS one less tableview and more Calendar.app (flowing text, not highly structured table).

**Comment by drewvolz** [comment]
> I want us to look at making the iOS one less tableview and more Calendar.app (flowing text, not highly structured table)

Absolutely.

**Comment by hawkrives** [comment]
Oops.

**Comment by hawkrives** [comment]
I was just going to wait for Eli and Matt to review.

**Comment by elijahverdoorn** [comment]
I approve for sure - the new look is great, good work @drewvolz.

**Pull request merged**
