### PR TITLE
Course Search: debounce search function, fix spacing of empty recent search list

### LINKED ISSUE #2432: Course Search: results are sometimes not displayed on search
I think we just need to debounce `performSearch` like in the student org view

### PR DESCRIPTION
**Pull request by hannesmcman**
This resolves #2432.

### CODE REVIEW

**Comment by hannesmcman** [comment]
I'm going to fix the spacing of the empty recent searches list too

**Review by hawkrives — DISMISSED** [review]
sure

**Comment by hannesmcman** [comment]
New empty recent searches look:
screen shot 2018-03-14 at 11 16 04 am

**Comment by hawkrives** [comment]
What do you think about just not showing anything there if there aren't any recent searches?

**Comment by hannesmcman** [comment]
Idk I kinda like it being there for the aesthetic...especially when thinking about what's going to go underneath it. I could probably be convinced otherwise though!

**Comment by hawkrives** [comment]
What if we added another section beneath it, of "suggested searches" or something? Then if there were no recent ones, it'd just show the suggestions, and if there were recent ones, they'd be above the suggestions.


Ideas for suggestions: pick a random deptnum from our data and suggest it; pick a random professor; pick a random word from a random course's description.

**Comment by hannesmcman** [comment]
I was thinking we could put a "Browse" section beneath it, where we'd have suggested filters, as well as an option to select as many filters as you want and give all the results that match those filters without having to type anything in the search bar..?

**Comment by hawkrives** [comment]
That sounds fancy. We can merge what you have here for now.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
