### PR TITLE
Revamp the dictionary view

### PR DESCRIPTION
**Pull request by hawkrives**
This is a first commit towards revamping the dictionary view to use a listview instead of collapsible rows.

It is nowhere near ready to go, yet.

Current status:

screen shot 2016-09-04 at 2 44 43 pm

screen shot 2016-09-04 at 2 45 03 pm

### CODE REVIEW

**Comment by hawkrives** [comment]
screen shot 2016-09-04 at 8 09 18 pm
screen shot 2016-09-04 at 8 03 50 pm

**Comment by drewvolz** [comment]
@hawkrives beautiful

**Comment by elijahverdoorn** [comment]
Looks good as usual, although you stole one of my ideas... :)

**Comment by drewvolz** [comment]
Closes #91
Closes #157

**Pull request merged**
