### PR TITLE
Release v2.6.0, β3

### PR DESCRIPTION
**Pull request by rye**
View [the comparison from v2.5.1](https://github.com/StoDevX/AAO-React-Native/compare/v2.5.1...v2.6.0-beta.3).
View [the comparison from v2.6.0-beta.1](https://github.com/StoDevX/AAO-React-Native/compare/v2.6.0-beta.1...v2.6.0-beta.3).
View [the comparison from v2.6.0-beta.2](https://github.com/StoDevX/AAO-React-Native/compare/v2.6.0-beta.2...v2.6.0-beta.3).

## Checklist
- [x] [Release PR]() successfully builds against `master` ([follow](https://circleci.com/workflow-run/dcdfa9b5-0189-43e8-926d-860cdefaa7f6))
- [x] Signed-off/approved
- [x] GitHub release notes drafted ([wiki](https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes#v260))
- [x] [Release PR]() merged to `master`.
- [x] GitHub release created
- [x] Tag build passes ([follow](https://circleci.com/workflow-run/3a147abd-58e6-4bc1-bcd1-8d350ad0ea44))

### CODE REVIEW

**Comment by hawkrives** [comment]
lol I can't open the b2...b3 diff on GitHub. I'll have to look locally. I'll do release notes at some point.

**Review by hawkrives — APPROVED** [review]

**Comment by rye** [comment]
Why is this marked as `pr/don't merge`?  It's ready to merge and it's been deployed.  Release notes are done separately anyhow.

**Comment by hawkrives** [comment]
It hasn't been deployed to iOS beta testers since there aren't release notes.

**Comment by hawkrives** [comment]
Changelog:

```markdown
- package updates
- update Oleville to https
- added Report a Dictionary Issue
- adds padding to the bottom of the homescreen notice
- moves BonApp menus to https
- fix TextInput scrolling on iOS
- sort courses by deptnum, instead of title
- change how course search searches (replace fuzzysearch with a hamming distance function)
- add Course Browsing functionality
- allow Menus to forget your selected meal between launches
- add Filters to course search
```

**Comment by hawkrives** [comment]
iOS beta has been released to beta testers.

**Pull request merged**
