### PR TITLE
Staged Hours update for week 35 (08-27—09-02)

### PR DESCRIPTION
**Pull request by rye**
- [ ] 1-1-cage.yaml
- [ ] 1-2-pause-kitchen.yaml
- [ ] 1-3-stav.yaml
- [ ] 1-4-bag-lunch-line.yaml
- [ ] 10-admissions.yaml
- [ ] 10-business-office.yaml
- [ ] 10-cmie.yaml
- [ ] 10-conferences-camps-events.yaml
- [ ] 10-financial-aid.yaml
- [ ] 10-osa.yaml
- [ ] 10-pastor-office.yaml
- [ ] 10-piper-center.yaml
- [ ] 10-registrar.yaml
- [ ] 2-1-bookstore.yaml
- [ ] 2-2-convenience-store.yaml
- [ ] 3-1-post-office.yaml
- [ ] 3-2-print-center.yaml
- [ ] 4-1-disco.yaml
- [ ] 4-2-halvorson-music-library.yaml
- [x] 4-3-rølvaag-library.yaml
- [ ] 4-4-rølvaag-reference-desk.yaml
- [ ] 5-1-it-helpdesk.yaml
- [ ] 5-2-asc.yaml
- [ ] 5-3-asc-speaking-space.yaml
- [ ] 5-4-asc-writing-desk.yaml
- [x] 6-1-skoglund.yaml
- [ ] 6-2-skoglund-pool.yaml
- [ ] 6-3-storp.yaml
- [x] 6-4-tom-porter.yaml
- [x] 6-5-tostrud-climbing-wall.yaml
- [ ] 7-1-wellness-center.yaml
- [ ] 7-2-health-services.yaml
- [ ] 7-3-sarn.yaml
- [ ] 7-4-gender-sexuality-center.yaml
- [x] 8-alh.yaml
- [x] 8-bc.yaml
- [x] 8-boe.yaml
- [x] 8-cad.yaml
- [x] 8-chm.yaml
- [x] 8-hh.yaml
- [x] 8-hom.yaml
- [x] 8-omh.yaml
- [x] 8-rms.yaml
- [x] 8-rns.yaml
- [x] 8-skifter.yaml
- [x] 8-tb.yaml
- [x] 8-toh.yaml
- [ ] 8-wlc.yaml
- [ ] 9-flaten-art-museum.yaml

### CODE REVIEW

**Comment by rye** [comment]
We should ship these soon.

**Review by hawkrives — DISMISSED** [review]

**Comment by rye** [comment]
Let's hold off until we've verified the hours changes from the latest update.

**Comment by rye** [comment]
OP updated with a checklist.

**Comment by rye** [comment]
Ehh, I'm just going to merge this now. We can update hours this weekend for next week.

**Comment by rye** [comment]
Well, I'll merge it once I get an approving review.

**Review by drewvolz — APPROVED** [review]
rslgtm 👍

**Pull request merged**
