### PR TITLE
Re-link the datetime picker for iOS and Android

### PR DESCRIPTION
**Pull request by drewvolz**
Fixes the crash on the platforms when trying to edit datetimes in the building hours editor.

### CODE REVIEW

**Review by rye — APPROVED** [review]

**Review by hawkrives — COMMENTED** [review]
Does it really require manual linking on android?

**Comment by drewvolz** [comment]
Android is in a half-linked state prior to this changeset so the button press didn't spawn the datetime picker. We can try removing all of the android linking and see what result we get if you'd like.

**Comment by hawkrives** [comment]
It's supposed to link automatically… so I would like that, if you don't mind. I tried to look at it this afternoon but got stuck on custom tabs again (which I've now forked, so we can fix it up)

**Comment by drewvolz** [comment]
I have now tested removal of the manual linking. I did not see the datetime picker appear in this case.

**Comment by hawkrives** [comment]
Ok. We'll leave it in.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
