### PR TITLE
Upgrade Xcode, macOS, iOS targets

### PR DESCRIPTION
**Pull request by drewvolz**
* bump to Xcode 15.2
* bump to macOS 14.2
* bump to iOS 17.2

---
- [macOS-14-readme actions runner-images](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md)
- Previously https://github.com/StoDevX/AAO-React-Native/pull/6982

### CODE REVIEW

**Comment by drewvolz** [comment]
I can lower the macOS runner target from 14.2 if we continue to get stuck at the following spot in CI
```
Waiting for a runner to pick up this job...
```

```
This request was automatically failed because there were no enabled runners online to process the request
for more than 1 days.
```

**Comment by rye** [comment]
New problem:

```console
/Users/runner/work/AAO-React-Native/AAO-React-Native/ios/AllAboutOlaf.xcodeproj: error: No profile for team 'TMK6S7TPX2' matching 'match AppStore NFMTHAZVS9.com.drewvolz.stolaf' found: Xcode couldn't find any provisioning profiles matching 'TMK6S7TPX2/match AppStore NFMTHAZVS9.com.drewvolz.stolaf'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'AllAboutOlaf' from project 'AllAboutOlaf')
note: Run script build phase 'Bundle React Native code and images' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'AllAboutOlaf' from project 'AllAboutOlaf')
```

**Comment by drewvolz** [comment]
- [ ] 1. Getting provisioning settled is one thing (although nightlies are somehow not broken from all this fun).

- [x] 2. Likely the next thing we'll come across is a build error related to depending on the newer Xcode 15 with the older React Native version of v71.1. 

    ```sh
    [21:48:49]: ▸ ::error file=/Users/runner/work/AAO-React-Native/AAO-React-    Native/ios/Pods/boost/boost/container_hash/hash.hpp,line=131,col=33::
                          no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
    [21:48:49]: ▸         struct hash_base : std::unary_function<T, std::size_t> {};
    [21:48:49]: ▸                            ~~~~~^~~~~~~~~~~~~~
    ```

    Once we leap upgrades in React Native itself, these changes can be unblocked. Last year work was started on https://github.com/StoDevX/AAO-React-Native/compare/master...drew/react-native-72-4 which stalled out due to `react-native-reanimated` incompatibilities for RN/iOS noted in https://github.com/StoDevX/AAO-React-Native/commit/5b678e03c71ab45cdd0b07fbdbaba729cdb44b15

    I think the compat is resolved in reanimated v3+ but what that means is more unknown compat upgrades for our other deps and then eventually react-native@73.

**Comment by drewvolz** [comment]
- [x] Part 2 from above should be handled in #7106.
- [x] Remaining is the provisioning profile match issue (which we can bypass, see below)

Since we do not run detox on nightlies, I've added a skip check for detox. `ci/skip-detox` label on PRs should bypass those failing provisioning checks for things we'd like to continue to check on nightlies and get into the main branch.

**Review by hawkrives — APPROVED** [review]

**Pull request merged**
