### PR TITLE
Stuff 'n' Nonsense

### PR DESCRIPTION
**Pull request by hawkrives**
aka `I have to touch everything`, `Praise be to Navbar`, `Glory to the Navbar`, `I should have gone to sleep a long time ago`.

This PR touches a lot of things.

It swaps out the tab bar icons for Ionicons, leaving the main icons as Entypo for "flavor".

It changes how screens are created and pushed, removing the need for the NavigatorScreen component entirely.

It shows the title of the previous screen in the Back button.

It uses a gold navigation bar. (I want to experiment with changing the color of the navbar based on the section of the app, but haven't been able to yet.)

It fixes most eslint complaints.

It attempts to solve the listview-padding problem.

Whee. Too much stuff for one PR. Apologies.

Why am I still up.

PS: I don't think we need the `flex: 1` that we've been putting on the containers anymore. I think I managed to automatically apply it from the root navigator onto whatever it renders.

### CODE REVIEW

**Comment by drewvolz** [comment]
This is massive. @elijahverdoorn later tonight would you be willing to check this on Android and I can double check on iOS?

**Comment by elijahverdoorn** [comment]
I'll test on Android. I'd also like to get a chance to read all the code before merging, it looks good from the glance I gave it, but for a major change like this I need a little more time with it.

**Comment by drewvolz** [comment]
It passed! Woo! :tada:

**Comment by elijahverdoorn** [comment]
Stuff I found in testing:
image
Overlap. I suggest using just a `<` as the back button so that the text doesn't have to move on Android.
image
Can we get rid of the edit button? I don't think that it serves any purpose.
image
Can we up the text size a little?

**Comment by hawkrives** [comment]
No, we'all just have to move the text on Android. I apologize: I didn't test this on Android last night. If we merge this, I'll bring Android up to the level of iOS tonight.

**Comment by elijahverdoorn** [comment]
I made a PR into this branch that does most of the things that I mentioned in my comment. See #151

**Comment by hawkrives** [comment]
Right. Silly me. :shakes head:

I left a few comments. 

Ooh, and you even set it to merge into here. Then we don't need to rush to merge this. Nice.

**Comment by drewvolz** [comment]
I've got a few notes from review. Some of these could most likely turn into issues of their own? I am a huge fan of the navigator and tab bar changes. I am happy to help out with any number of these issues.

##### What this review is directly responsible for:
- [x] #153 – News story detail view loads `undefined` (not oleville)
- [x] #155 – It is weirdly possible to hit the `settings` button quickly enough to summon multiple instances of the settings menu. They appear to be pushed onto the view stack. I can mash the mutton 4 or 5 times, and have become stuck in that state and cannot pop-back. If you push another view (credits/privacy/legal) you can get it to let you pop the settings view. At this point, I am returned this warning:
  
  > Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

I am trying very hard to break our app. I imagine the fix being to _immediately_ disable the button once it has been pushed until another view appears.

##### Other issues found in general
- [ ] #147 – Scrollbar fix leads to content being overlapped by the tab bar
- [x] #156 – KSTO streaming media needs to have an exception made for it (app transport security)
- [x] #158 – Text in Important Contacts should be centered much as you did in Transportation (other modes)
- [ ] #157 – Dictionary view stutters when pushing and popping from the view

**Comment by hawkrives** [comment]
Oh yeah, I forgot to the the news story view. I'll get that now.

**Comment by hawkrives** [comment]
Now we just wait for the builds…

**Comment by hawkrives** [comment]
@elijahverdoorn You added margin to line up the android back button, right?

**Comment by elijahverdoorn** [comment]
@hawkrives Yeah

**Comment by hawkrives** [comment]
@elijahverdoorn Do you want to merge or shall I? (I don't care about waiting for Appveyor.)

**Comment by elijahverdoorn** [comment]
Special thanks to @hawkrives for this major improvement to the codebase. Great work. I approve this PR! :shipit:

**Comment by hawkrives** [comment]
even better, I actually made a PR for it! 😝 

thanks for the feedback, you two! Much appreciated.

**Pull request merged**
