### PR TITLE
[course Search]: Add Course Notes to List Row

### LINKED ISSUE #2948: [course search] Course notes should be shown on the list view
GitHawk Upload by hawkrives

Notes are the italic bits in the screenshot above.

### PR DESCRIPTION
**Pull request by hannesmcman**
Resolves #2948.

screen shot 2018-09-04 at 8 25 07 am

### CODE REVIEW

**Review by rye — APPROVED** [review]

**Comment by hawkrives** [comment]
Why the newline at the end of all of the notes?

**Comment by hawkrives** [comment]
Oh, because you put them first. I'd just have wrapped it in a View.

**Comment by drewvolz** [comment]
Did we opt to not show the notes in the detail for some reason?

**Comment by drewvolz** [comment]
I want to either remove this from the list rows, or limit them to 1 line. Showing the whole text is too much on the rows. They certainly deserve their own unrestricted section in the detail.

~ | ~
--|--
telegram-cloud-file-3-831937890-90711-7770742396837060420 | telegram-cloud-file-3-830932384-97183-1821923187031404446
telegram-cloud-file-3-830932499-97272--4431890308569011349

**Comment by hawkrives** [comment]
@drewvolz open a new issue please

**Pull request merged**
