### PR TITLE
Bump @sentry/react-native to v2.0.1

### PR DESCRIPTION
**Pull request by rye**
Part of #4931; see that issue for more background.

It's strongly recommended to consult the [migration guide](https://docs.sentry.io/platforms/react-native/migration/#from-1x-to-2x) which gives us some information about what's part of this release.

Left to do:

- [x] Upgrade our sentry server to greater than `20.6.0`. (Take a backup first.)
- [x] Update pods

### CODE REVIEW

**Review by rye — COMMENTED** [review]
This will need a CocoaPods update.

**Comment by drewvolz** [comment]
@rye pods for sentry updated!

**Review by rye — COMMENTED** [review]
✅

**Review by drewvolz — APPROVED** [review]

**Comment by drewvolz** [comment]
Hmm

```
▸ Compiling RNSentry.m

❌  /Users/runner/work/AAO-React-Native/AAO-React-Native/node_modules/@sentry/react-native/ios/RNSentry.m:151:54: no visible @interface for 'SentryClient' declares the selector 'fileManager'

[[[[SentrySDK currentHub] getClient] fileManager] storeEnvelope:envelope];
```

**Comment by rye** [comment]
@drewvolz that error [appears to be fixed in version 2.0.1](https://github.com/getsentry/sentry-react-native/releases/tag/2.0.1) 😅

Upgrading…

**Comment by rye** [comment]
@drewvolz if you could update the pods once more, I think it should work

**Review by drewvolz — APPROVED** [review]

**Review by rye — COMMENTED** [review]
✅

**Pull request merged**
