### PR TITLE
[modularization] Re-export react-native-tableview-simple and put our custom cells into a module

### PR DESCRIPTION
**Pull request by hawkrives**
Two things:

1. Moves the "components/cells" custom TableView cells into a module, `@frogpond/tableview`.
2. Re-exports the TableView, Section, and Cell components from `react-native-tableview-simple`

I'm aiming to get to where we can design with TableView and style appropriately for Android/iOS, and I think that `@frogpond/tableview` is where we should expose that to our app.

Also, it'll let us have one place to set defaults for the app, like setting the Section's background color.

Neither of those things have yet been implemented.

Part of the great #1537 redo.

### CODE REVIEW

**Review by rye — APPROVED** [review]

**Review by drewvolz — DISMISSED** [review]

**Review by rye — DISMISSED** [review]

**Comment by rye** [comment]
This could use a sanity check post-rebase. I had a merge conflict.

**Review by hawkrives — COMMENTED** [review]
LGTM

**Comment by hawkrives** [comment]
Except for the fact that it needs more commits

**Comment by rye** [comment]
Okay, I'll just merge the appropriate branch, then.

**Review by rye — APPROVED** [review]
Flow passes locally, and this PR is now atomic.

**Pull request merged**
