### PR TITLE
Course Search: fix search bug

### LINKED ISSUE #2432: Course Search: results are sometimes not displayed on search
I think we just need to debounce `performSearch` like in the student org view

### LINKED ISSUE #2492: Course Search: Search results sometimes don't update
After some testing, it seems that if the user presses enter too quickly after finishing typing their search, the results do not update. This probably has something to do with nesting the `executeSearch` function within the `setState` call. This only happens when there are active filters.

### PR DESCRIPTION
**Pull request by hannesmcman**
Resolves #2432.
Resolves #2492.

Hawken and I had a long comment thread about this in #2383 and so I've decided to bring this bug fix to another PR. For some reason, and I'll be honest I don't know why, the call to `this.setState` does not work properly when the `executeSearch` function is called within it, but it works fine if the results of `executeSearch` are stored in a variable, which is in turn passed to `this.setState`.

Doesn't work:
```javascript
this.setState(() => executeSearch({
	text: query,
	filters: this.props.filters,
	applyFilters: this.props.applyFilters,
	allCourses: this.props.allCourses,
	updateRecentSearches: this.props.updateRecentSearches,
}))
```

Works:
```javascript
const results = executeSearch({
	text: query,
	filters: this.props.filters,
	applyFilters: this.props.applyFilters,
	allCourses: this.props.allCourses,
	updateRecentSearches: this.props.updateRecentSearches,
})
this.setState(() => results)
```

I've tested this considerably and this change does eliminate the bug as far as I can tell. While it definitely seems at first glance that these two code snippets are functionally equivalent, my suspicion is that we're missing something subtly different between them that causes the latter to work. Thoughts?

### CODE REVIEW

**Review by rye — APPROVED** [review]

**Review by hawkrives — CHANGES_REQUESTED** [review]
I still don't know what's going on, but I don't want to merge this as-is because it's only moving a race condition around IMO.

**Comment by hannesmcman** [comment]
But if it there were a race condition in the second option, wouldn't it only work some of the time? I've tested it a whole bunch of times and it has never not worked... @hawkrives 

I know I'm not giving you a satisfying explanation for how it's functionally different from what we have now, but I just don't have the time right now to dive into the RN docs to search for the difference..I personally don't see the harm in merging this if it solves a bug that is the only major hold on shipping course search..

**Comment by drewvolz** [comment]
#2502 is an additional blocker on course search fwiw

**Comment by rye** [comment]
Needless to say, this works for me. I have no clue why we don't just merge this and try it and production?

**Review by rye — APPROVED** [review]

**Comment by hawkrives** [comment]
It does work. 

I haven't wanted to merge it because it's just moving a race condition somewhere else, where it's harder to trigger, because the two implementations should be equivalent.

**Review by rye — COMMENTED** [review]
Without knowing much about JS' internals, I have the two following observations:

- This seems to fix the underlying problem. I've tried it out a bunch and the issue we were having before no longer exists, or happens much less frequently at least.

- `() => [non-const return value from executeSearch]` should, in my opinion, be very different from `() => [const]`. I think that's what the underlying problem is, or…

I can't think of anything else, so I feel we need to either say this is okay for nightly testing (because it simply moves the evaluation and doesn't change the functional outcome of the method) or come up with a reason why this needs to change.

Personally, I'd rather test this in our nightly group where we can at least get real stack traces to indicate where the race condition is "moved to."

**Review by hawkrives — APPROVED** [review]
I have a WIP that solves whatever problem is here by avoiding the need to call executeSearch here entirely, so meh sure we can merge this.

**Comment by hawkrives** [comment]
@rye do note that all "const" means in JS-land is that the variable name can not be rebound. That's all. (ie, no "const x= 2; x=3".)

**Comment by hannesmcman** [comment]
@StoDevX/all-about-olaf can someone merge this?

**Comment by rye** [comment]
Done.

**Pull request merged**
