### PR TITLE
Greenkeeper/react navigation 1.5.7

### PR DESCRIPTION
**Pull request by drewvolz**
Supersedes and closes #2306

* Adds back `lazy` tab support
* Fixes our missing tabbar icons

### CODE REVIEW

**Comment by hawkrives** [comment]
lazy was re-added in https://github.com/react-navigation/react-navigation/pull/3538

Sure, let's nightly it

**Review by hawkrives — APPROVED** [review]

**Comment by hannesmcman** [comment]
The build failed when I tried to run this on my simulator
```
In module 'Mapbox' imported from /Users/Hannes/AAO-React-Native/node_modules/@mapbox/react-native-mapbox-gl/ios/RCTMGL/MGLOfflineModule.h:12:
/Users/Hannes/AAO-React-Native/node_modules/@mapbox/react-native-mapbox-gl/ios/Mapbox.framework/Headers/MGLCircleStyleLayer.h:20:5: note: 'MGLCircleScaleAlignmentMap' declared here
    MGLCircleScaleAlignmentMap,
    ^


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Hannes/AAO-React-Native/ios/build/Build/Intermediates.noindex/RCTMGL.build/Debug-iphonesimulator/RCTMGL.build/Objects-normal/x86_64/RCTMGLStyle.o RCTMGL/RCTMGLStyle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by hawkrives** [comment]
Also, what did you change to bring back tab bar icons?

**Comment by hawkrives** [comment]
Hannes: make sure that your Xcode project isn't modified locally. Mapbox can be finicky, but that shouldnt be related in any way to this PR (which only touches the JS side)

**Comment by drewvolz** [comment]
> Also, what did you change to bring back tab bar icons?

Updated the version of react-navigation to 1.5.7

**Comment by hawkrives** [comment]
And they just magically reappeared? Huh.

**Pull request merged**
