### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by hawkrives**
Upgrade react to 15.2.1, and react-native to 0.31.

Also fixes bugs that popped up in master as a result of the upgrade.

### CODE REVIEW

**Comment by drewvolz** [comment]
Fails to run. Something about a local copy of keys you are using?

`import * as k from '../../keys'` results in `unable to resolve module`.

**Comment by elijahverdoorn** [comment]
Approved. Merging this one myself so that my upcoming changes are based on it.

**Comment by drewvolz** [comment]
Would it be advantageous to setup [greenkeeper](https://greenkeeper.io/) to automatically make PRs for upgrading dependencies? @hawkrives was your experience using greenkeeper positive?

**Comment by hawkrives** [comment]
Yes. The only thing is that after you upgrade react-native, you have to run `react-native upgrade`, but we'd have to remember to do that anyway.

(I already upgraded the files in this repo.)

**Comment by hawkrives** [comment]
Greenkeeper should now be enabled.

**Comment by hawkrives** [comment]
We'll know it is if we start getting PRs from a greenkeeper bot 😄

**Comment by drewvolz** [comment]
Awesome!

**Comment by hawkrives** [comment]
See #34 – looks like it's running

**Pull request merged**
