### PR TITLE
Revamp the calendar view

### PR DESCRIPTION
**Pull request by hawkrives**
~~WIP.~~

Ready.

### CODE REVIEW

**Comment by hawkrives** [comment]
Current status screen shot 2016-09-04 at 8 52 22 pm

**Comment by hawkrives** [comment]
Before

screen shot 2016-09-04 at 9 24 48 pm

After 

screen shot 2016-09-04 at 9 23 30 pm
screen shot 2016-09-04 at 9 23 36 pm

**Comment by hawkrives** [comment]
Inspired by ("stolen from") the iOS calendar view

img_6776

**Comment by drewvolz** [comment]
This looks phenomenal. I wish I could test it this weekend.

**Comment by drewvolz** [comment]
Works well on iOS. Need a confirmation for Android.

**Comment by elijahverdoorn** [comment]
Tested, merging so that I can publish it.

**Comment by hawkrives** [comment]
Thanks!

**Pull request merged**
