### PR TITLE
[modularization] Move FilterView to a new module

### PR DESCRIPTION
**Pull request by hawkrives**
Moves the "filter" components into a module, `@frogpond/filter`.

Part of the great #1537 redo.

Closes #2895. (because it includes it)

### CODE REVIEW

**Review by rye — DISMISSED** [review]

**Review by drewvolz — DISMISSED** [review]

**Comment by rye** [comment]
This PR could use a sanity check post-rebase.

**Comment by hawkrives** [comment]
So if this doesn't include the commits from #2893, how can https://github.com/StoDevX/AAO-React-Native/pull/2896/files#diff-40d4f57836a110fe35c2488ee1c1a70bR17 work?

**Comment by hawkrives** [comment]
Needs #2893

**Comment by rye** [comment]
Also needed #2894 and #2895. Flow is happy locally, so this should pass.

**Review by rye — APPROVED** [review]
Atomic PR! Yay!

**Pull request merged**
