### PR TITLE
React Navigation 2.0

### PR DESCRIPTION
**Pull request by hawkrives**
wow

https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html

- i cant even: "State persistence - automatically save state and reload it when the app restarts" https://github.com/react-navigation/react-navigation/pull/3716
- `XNavigator(...)` is now `createXNavigator(...)`
- `this.props.navigator.navigate()` now automatically re-uses previous views, which should fix the long-standing double-push bug (#155)

I kinda want to merge this and look at it tomorrow and file issues to fix things then

### CODE REVIEW

**Comment by drewvolz** [comment]
We should at least try to fix the breaking changes before we merge

**Comment by hawkrives** [comment]
The rename isn't breaking; it's a deprecation, since they're not removing the old way until v3.

**Comment by hawkrives** [comment]
That is to say, this should "just work" if we merge tonight with no further changes.

**Review by drewvolz — APPROVED** [review]

**Comment by drewvolz** [comment]
@hawkrives has to say

> it doesn't work yet

**Review by drewvolz — DISMISSED** [review]
it don't work yet

**Comment by hawkrives** [comment]
Hokay.

Other changes, now: 

- Android now has the fancy new Material bottom tabs
- They're black on gold
- To match that, the titlebar is also black on gold. I ask that we sit with it for a day+ before looking for other colors (dark gray?)

---

Also, React Navigation changed how you define the title on a TabNavigator; it's now much closer to how you define it on an individual screen.

That is, instead of passing it as the second argument to TabNavigator, you just set `myTabNav.navigationOptions = {title: 'MyTitle'}`.

---

Oh, and Prettier reformatted the TabNavigators because there's only one argument now.

**Review by drewvolz — APPROVED** [review]

**Pull request merged**
