### PR TITLE
Remove push notifications from the app

### PR DESCRIPTION
**Pull request by hawkrives**
- We've never hooked them up
- The iOS "Push Notifications" entitlement is a pain for external developers
- We've never hooked them up

### CODE REVIEW

**Comment by hawkrives** [comment]
… apparently _none_ of my fancy Danger Xcode/Android checks work right. I swear I tested them…

**Comment by drewvolz** [comment]
I have a hope that we’ll one day use them. But doesn’t mean anything.

**Review by drewvolz — APPROVED** [review]
If we do use them... I guess we’ll put the work back. So I guess nix them.

**Comment by hawkrives** [comment]
@drewvolz My thinking is that none of the other partially-complete work we keep around causes trouble for people, and we tend to remove it when it does (e.g., rn-view-shot, for me.)

This has never even been functional past a "log to the console when I get a push maybe" state, so I don't think it's worth keeping around at _all_.

@rye?

**Comment by hawkrives** [comment]
oops

**Comment by drewvolz** [comment]
Yeah. One day we’ll find a decent use for push. But for now it is a headache for everyone. When this passes, I am fine with merging it. I would like to hear from other developers on this project, though.

**Review by rye — APPROVED** [review]
Some day we'll get there, but yeah.  Go on ahead.

**Pull request merged**
