### PR TITLE
Refactoring of Filter Popover

### PR DESCRIPTION
**Pull request by hannesmcman**
I’m ok with all these changes!

### CODE REVIEW

**Comment by hawkrives** [comment]
oops apparently I didn't run lint. I'll fix those.

**Comment by hawkrives** [comment]
now linted

**Review by hawkrives — COMMENTED** [review]
/me approves own changes

**Comment by hannesmcman** [comment]
wish there was a "merge when checks have passed" option in github

**Comment by hannesmcman** [comment]
Do we really need to run builds on PR's into non-master branches? Seems a little overkill since they'll be run on those branches anyway once the PR is merged... @hawkrives @rye

**Comment by hawkrives** [comment]
@hannesmcman Technically we run builds on every pushed commit, not just every PR… I do want to work on running things in a "smarter" fashion, where we can tell, say, "this branch only changes data files, so we don't need to lint or build it".

Actually

@rye https://github.com/danger/peril is a bot thing we can run and configure and it has a "merge on green" command

image

**Pull request merged**
