### PR TITLE
Northfield calendar

### PR DESCRIPTION
**Pull request by drewvolz**
Northfield events from the http://visitingnorthfield.com calendar.

thisisnorthfield

### CODE REVIEW

**Comment by drewvolz** [comment]
We may have to make an adjustment to the calendar. A few of these times look wrong with the start/end time being the same.

**Comment by hawkrives** [comment]
Sure. How about a thing that says "hide the end time if start === end"?

Great work!

**Comment by hawkrives** [comment]
(Such a change should probably be a separate PR.)

**Comment by drewvolz** [comment]
Could there be a way to increase the end time by one if they are listed as the same? To remain consistent with the other calendars?

**Comment by hawkrives** [comment]
We don't know that they're an hour long, though? They might be two or something. At first blush, I'd prefer to just hide the end time if we don't know how long they'll go.

**Comment by drewvolz** [comment]
So you are thinking that events listing start/end as the same may not be one hour in length. Alright, I guess we cannot assume that. I'll aim for your original suggestion.

**Comment by hawkrives** [comment]
Now for the important question: I feel like this should be the third tab, rather than the middle one, in order to provide priority to on-campus events.

[ `St. Olaf` | `Oleville` | `Student Orgs` | `Northfield` ]

**Comment by drewvolz** [comment]
Sure, that will be moved back to its original order.

**Review by hawkrives — APPROVED** [review]
Man. Look at that diff. That's a nice diff.

**Comment by hawkrives** [comment]
@elijahverdoorn We've opted to give you final say on adding this, since it kinda falls under the "new feature" umbrella.

**Comment by elijahverdoorn** [comment]
I'm in favor of the idea, but want to make sure that the ordering of tabs is St. Olaf, Oleville, Northfield. That's the order that the code would suggest, but the screenshot that @drewvolz has doesn't match. Assuming that the order is what the code has and not the screenshot, go for it.

**Comment by hawkrives** [comment]
Yes. We updated the order after the screenshots were taken. He couldn't update the screenshots today, but it's definitely Olaf, Oleville, Northfield.

**Comment by elijahverdoorn** [comment]
@hawkrives Thanks for the confirmation.

**Pull request merged**
