### PR TITLE
Skoglund pool interim hours

### PR DESCRIPTION
**Pull request by drewvolz**
**Lap Swim**

Days | Times
--|--
Monday thru Friday | 12:00 – 2:00 p.m
Monday, Wednesday, Friday | 6:00 – 8:30 p.m.

**Open swim**

Days | Times
--|--
Tuesday, Thursday | 8:00 – 10:00 p.m.
Saturday, Sunday | 2:00 – 4:30 p.m.

[Image for reference](https://user-images.githubusercontent.com/5240843/34743328-9d90fbec-f546-11e7-9620-8b98f745ef5a.jpg) provided by @hawkrives

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]
Something tells me that we had the wrong hours before…

Thanks!

**Comment by drewvolz** [comment]
This is verbatim what is on the [website](https://wp.stolaf.edu/recreation/facility-hours/), and I think it differs with this PR and with the image attached to this PR. Notice how there is only 1 lap swim and 3 open swim entries?

<hr>
Pool Hours:   Interim  *** Note some Changes in evening swim hours *******

12:00 p.m. -2 :00 p.m.- Lap swim, Monday – Friday.
6:o0-8:30 p.m.- open swim, Monday, Wednesday, Friday.
8:00-10:00 p.m. – open swim – Tuesday, Thursday.
2:00-4:30 p.m.-open swim, Saturday/Sunday.

**Comment by drewvolz** [comment]
I take issue with the formatting, but that's another issue... a zero being an o, the mixed dashes and em dashes, etc.

**Comment by hawkrives** [comment]
I'm, er, wow.

I'm going to ask Dan if I can edit that page tomorrow, maybe something like this instead https://wp.stolaf.edu/recreation/facility-hours-2

**Comment by drewvolz** [comment]
I really like the page you linked

**Pull request merged**
