### PR TITLE
Pause late night menu hours

### LINKED ISSUE #508: [discussion] Add "late night" hours to the Pause hours?
Should we add "late night" to the pause hours view? Like how the Cage has a separate Late Night set.

### PR DESCRIPTION
**Pull request by drewvolz**
This adds the schedule for the Pause late night menu. Fridays and Saturdays from 9pm to 2am.

Closes #508 

Main | Detail
---|---
main | detail

### CODE REVIEW

**Comment by hawkrives** [comment]
You'll need to run "npm run bundle-data" and commit the changed file in docs, as well, or Travis ought to fail.

**Review by hawkrives — APPROVED** [review]
LGTM.

**Comment by hawkrives** [comment]
Oh. Last thing: you notice how there's Late Night, and no label for the other line?

It automatically hides the Hours label. So we'll need to change it to something else, maybe "Daylight"?

**Comment by drewvolz** [comment]
Changed.

Main | Detail
---|---
main | detail

**Review by hawkrives — APPROVED** [review]
W00t!

**Pull request merged**
