### PR TITLE
README Style Tweaks

### PR DESCRIPTION
**Pull request by rye**
This PR:

- Consolidates CI badges into the title
- Adds "Get it on Google Play" and "Download on the App Store" badges, linking to the appropriate places
- Re-orders and updates "Getting Started" instructions
- Turns "Note" section into a bulleted list
- Emboldens types of contributions in "Contributing" section.
- Adds legal notices for use of "Google Play", "iPhone", "iPad", and "the Apple logo" in documentation and the app itself

### CODE REVIEW

**Review by drewvolz — APPROVED** [review]
Sure, looks like a nicer readme. Thanks @rye

**Comment by hawkrives** [comment]
My only thing is that I don't like having the badges on the same line as the title

**Comment by drewvolz** [comment]
If we have the badges, should we remove the download links and keep the beta links?

**Comment by rye** [comment]
Why not, @hawkrives? I think it looks fine, especially with &middot; between.

Once I'm done with lunch, I can yank the download links as they are now redundant.

**Review by hawkrives — APPROVED** [review]
Meh sure

**Pull request merged**
