### PR TITLE
Migrate to React-Navigation

### LINKED ISSUE #506: Back button / screen title sometimes intersect
See "late night breakfast" on a 5s.

### LINKED ISSUE #578: NoticeView extends beneath a tab bar
It's not quite centered:

I'm not entirely sure how to fix it. We might just let it lie…

### LINKED ISSUE #590: Top Menu Bar Button Alignment Off on Non-Default Font Sizes
In the attached screenshots, you can see that the button and text in the top menu bar is/are misaligned.  My phone uses the "Small" Android Display font size, and I believe that is what causes this.  Shouldn't this be dynamically centered vertically, or is that not possible/easy?

I'm running version `2.0.0-beta.1`.

### LINKED ISSUE #1146: Move to react-navigation
From the release notes for https://github.com/facebook/react-native/releases/tag/v0.44.3:

> Navigator has been deprecated in favor of [React Navigation](https://reactnavigation.org/). If you wish to continue using Navigator, you can install the [react-native-deprecated-custom-components](https://github.com/facebookarchive/react-native-custom-components) package which provides the legacy Navigator component.

I have a local branch that I'll push soon that starts us down this road. It accidentally grew into a "let's rework News to use redux" branch too, so I'll try to remove that and just make a "replace Navigator with React Navigation" branch. (pushed at [`react-navigation`](https://github.com/StoDevX/AAO-React-Native/tree/react-navigation))

<details><summary>current status</summary> 

image

note the lack of toolbar buttons
</details>
<br/>

IIRC, the current status is:

- no nav buttons on the toolbar on the homescreen
    - the Edit button is doable, but I don't think it supports left-side custom components. We'll have to investigate that.
- It's a pretty major departure from the old navigation style, but I think I can take what I learned from that branch and make a less invasive change PR.
    - namely, when I started that migration I didn't think you could pass objects to child routes, which we rely on heavily for e.g. News stories; I later figured out how to pass objects. That's why I started moving more stuff into Redux, but I should be able to separate those two changes now.

### PR DESCRIPTION
**Pull request by hawkrives**
> This doesn't migrate the storybook… which we've mostly forgotten about anyway.

Known issues:
- The Carleton menu's list doesn't update the header info when you open a menu
- ~~I haven't tested on Android~~ Drew tested on Android today
- ~~App settings are currently inaccessible~~
- Background colors are different between react-navigation and react-native-tableview-simple

---

This PR moves us to React Navigation.

It's… pretty different. Docs live at https://reactnavigation.org/docs/intro/.

Tab screens are now defined like this:

```js
export default TabNavigator(
  {
    ExpressLineBusView: {
      screen: () => <BusView line="Express Bus" />,
      navigationOptions: {
        tabBarLabel: 'Express Bus',
        tabBarIcon: TabBarIcon('bus'),
      },
    },

    RedLineBusView: {
      screen: () => <BusView line="Red Line" />,
      navigationOptions: {
        tabBarLabel: 'Red Line',
        tabBarIcon: TabBarIcon('bus'),
      },
    },

    BlueLineBusView: {
      screen: () => <BusView line="Blue Line" />,
      navigationOptions: {
        tabBarLabel: 'Blue Line',
        tabBarIcon: TabBarIcon('bus'),
      },
    },

    TransportationOtherModesListView: {
      screen: OtherModesView,
    },
  },
  {
    navigationOptions: {
      title: 'Transportation',
    },
  },
)
```

Note that if you don't need to pass any props to the component, such as in OtherModesView, you can just provide a reference to the component.

If you need to provide props, such as on a menu, news list, or bus route, you should also inline the navigationOptions into the tabbed nav, instead of defining it on the component, as the component is only defined once. However, if there aren't multiple copies of the component floating around, such as Balances, Student Jobs, or Other Modes, you should define the navigationOptions on the component directly.

---

In order to add a new screen to the top level, you now add a key/value pair to the big object thing in `source/navigation.js`:

```js
export const AppNavigator = StackNavigator(
  {
    HomeView: {screen: HomeView},
    BuildingHoursDetailView: {screen: BuildingHoursDetailView},
    BuildingHoursView: {screen: BuildingHoursView},
    CalendarView: {screen: CalendarView},
    ContactsView: {screen: ContactsView},
    CreditsView: {screen: CreditsView},
    DictionaryDetailView: {screen: DictionaryDetailView},
    DictionaryView: {screen: DictionaryView},
    EditHomeView: {screen: EditHomeView},
    EventDetailView: {screen: EventDetailView},
    FaqView: {screen: FaqView},
    FilterView: {screen: FilterView},
    HelpView: {screen: HelpView},
    JobDetailView: {screen: JobDetailView},
    LegalView: {screen: LegalView},
    MenusView: {screen: MenusView},
    NewsItemView: {screen: NewsItemView},
    NewsView: {screen: NewsView},
    PrivacyView: {screen: PrivacyView},
    SettingsView: {screen: SettingsView},
    SISLoginView: {screen: SISLoginView},
    SISView: {screen: SISView},
    // SnapshotsView: {screen: SnapshotsView},
    StreamingView: {screen: StreamingView},
    StudentOrgsDetailView: {screen: StudentOrgsDetailView},
    StudentOrgsView: {screen: StudentOrgsView},
    TransportationView: {screen: TransportationView},
  },
  {
    navigationOptions: {
      headerStyle: {
        backgroundColor: c.olevilleGold,
      },
      headerTintColor: c.white,
    },
  },
)
```

---

To open a new screen, you now call the `props.navigation.navigate`.

```js
this.props.navigation.navigate('NewsItemView', {story})
```

The first arg is the `key` half of the key/value pair defined in a navigator somewhere above the call to `navigate`. The second is the parameters provided to the incoming screen; they're provided to the component under `this.props.navigation.state.params` (yes, that's a really long name.)

---

Things I got to get rid of:

- NoRoute
- react-native-tab-view
- The custom styles for the navigation bar
- The BackAndroid logic
- My custom TabbedView wrappers (kinda)
- This whole thing: 

    ```diff
    openFilterView = () => {
    -    this.props.navigator.push({
    -      id: 'FilterView',
    -      index: this.props.route.index + 1,
    -      title: 'Filter',
    -      sceneConfig: 'fromBottom',
    -      onDismiss: (route: any, navigator: any) => navigator.pop(),
    -      props: {
    -        pathToFilters: ['menus', this.props.name],
    -        onChange: filters => this.props.onFiltersChange(filters),
    -      },
    +    this.props.navigation.navigate('FilterView', {
    +      pathToFilters: ['menus', this.props.name],
    +      onChange: filters => this.props.onFiltersChange(filters),
        })
    }
    ```

---

I think that's everything. R&R?

Closes #506 
Closes #578?
Closes #590 
Closes #1146

### CODE REVIEW

**Comment by hawkrives** [comment]
yeah, sorry @stodevx-bot:

> We like to try and keep PRs under 400 lines, and this one was 2189 lines.

**Comment by hawkrives** [comment]
I… probably shouldn't have merged those PRs from Drew. Apologies for the increased size.

**Review by drewvolz — APPROVED** [review]
You and I tested this today pretty thoroughly. I’m pretty sure it works well enough.

**Comment by hawkrives** [comment]
@elijahverdoorn For reviewing this PR, you'll probably want to focus on two separate views of the changes: https://github.com/StoDevX/AAO-React-Native/compare/master...445d934f0bc17a37127fee5b1d1766a22b94e2f3 and https://github.com/StoDevX/AAO-React-Native/compare/445d934f0bc17a37127fee5b1d1766a22b94e2f3...react-navigation-take2. The first one is the content of this PR before @drewvolz's PRs, and the second is with them.

**Comment by hawkrives** [comment]
I would like to fix the remaining "known issues" after we merge this, tbh. Thx.

**Comment by hawkrives** [comment]
I heard back from Eli out-of-band. I'm merging this.

**Comment by hawkrives** [comment]
… after I merge the other PRs into here

**Comment by hawkrives** [comment]
> We like to try and keep PRs under 400 lines, and this one was 2960 lines.

**Comment by hawkrives** [comment]
> We like to try and keep PRs under 400 lines, and this one was 3095 lines.

**Comment by hawkrives** [comment]
> We like to try and keep PRs under 400 lines, and this one was 5019 lines.

**Comment by hawkrives** [comment]
> We like to try and keep PRs under 400 lines, and this one was 5698 lines.

**Pull request merged**
