### PR TITLE
add coordinates to the Blue Line

### PR DESCRIPTION
**Pull request by hawkrives**
I found all of them but South Oaks Apartments and Ensley Apartments.

### CODE REVIEW

**Comment by hawkrives** [comment]
Drew found their map: http://threeriverscap.org/sites/default/files/complete_nf_brochure.pdf

**Comment by elijahverdoorn** [comment]
Is this for RN maps (the airbnb one)??

**Comment by hawkrives** [comment]
@elijahverdoorn Yeah, we currently have one for the express bus, and nothing else.

**Comment by elijahverdoorn** [comment]
Gotcha. I saw this package and had the same thought, glad that it's being done.

**Review by elijahverdoorn — APPROVED** [review]

**Pull request merged**
