### PR TITLE
[RFC] Add link to StoPrint from the homescreen

### PR DESCRIPTION
**Pull request by hawkrives**
I really think this would be useful.

Thoughts?

// cc @elijahverdoorn 

Part of #78

### CODE REVIEW

**Comment by hawkrives** [comment]
@drewvolz:
> I would take this approach: check when opening the parts that are relevant to the parts we care about being relevant. If not on the sto network, then render a NoticeView and explain they're not on the right wifi network

We'll push this out later, via codepush, once we have an error view ready.

**Comment by hawkrives** [comment]
Now that I'm on campus, I can actually check to make sure this works… w00t.

**Comment by drewvolz** [comment]
I am willing to approve of this if we can render a `NoticeView` for users that are not on campus.

**Comment by hawkrives** [comment]
Someone stop me before I just implement a native view for it. There's no mobile site; it's just the desktop version.

**Comment by hawkrives** [comment]
OTOH, it's really simple – a plain html table, with a link to "release" and "cancel" for each row, which are implemented as just simple HTTP requests. No JS magic here.

**Comment by drewvolz** [comment]
Initial work on a native implementation is happening on the [stoprint-take-2](https://github.com/StoDevX/AAO-React-Native/tree/stoprint-take-2) branch.

**Pull request closed without merging**
