### PR TITLE
Add some... interesting Home screen notices

### PR DESCRIPTION
**Pull request by rye**
Yeah. Probably not the best of ideas, but I'm curious to see if they work.

### CODE REVIEW

**Review by hawkrives — DISMISSED** [review]
we should do this for a bit, just for nightly… don't need to ship it

**Comment by drewvolz** [comment]
Add a shipping hold to it, then?

**Comment by rye** [comment]
Yeah I kinda just want to see this once in a nightly and then probably revert the crazy ones at least.

**Review by drewvolz — APPROVED** [review]

**Review by hawkrives — APPROVED** [review]

**Comment by rye** [comment]
Here at [StoDevX/AAO-React-Native](/StoDevX/AAO-React-Native) we ship the _real_ features. 😉

Merging.

**Comment by drewvolz** [comment]
We could introduce the concept of `development` notices?

**Comment by drewvolz** [comment]
Oh... too late.

**Comment by rye** [comment]
Yeah, that would be out of scope. We can do that in another PR, though! (I will probably queue a PR to delete the new weird notices and put a don't-merge/shipping-hold combo on that.)

**Pull request merged**
