### PR TITLE
Update faqs

### PR DESCRIPTION
**Pull request by drewvolz**
Remove the news api faq.. it is back up and running.

### CODE REVIEW

**Review by hawkrives — COMMENTED** [review]
You edited the json manually, didn't you?

**Comment by drewvolz** [comment]
Yes

**Comment by hawkrives** [comment]
You'll need to run the command then because something didn't work.

**Comment by drewvolz** [comment]
Some test failed

**Comment by hawkrives** [comment]
I re-ran the build and it passed.

**Pull request merged**
