### PR TITLE
Release v2.4.1

### PR DESCRIPTION
**Pull request by rye**
View [the comparison](https://github.com/StoDevX/AAO-React-Native/compare/v2.4.0...release-v2.4.1).

# Release notes (from [the wiki](https://github.com/StoDevX/AAO-React-Native/wiki/Release-Notes#v241))

```markdown
Hey Oles! We're proud to announce version 2.4.1, bringing working SIS balances back among many other things!

# FIXES #
• SIS balances work again! We also added additional meal plan information. You should still trust Stav's staff more, but we're getting better at things!
• A bunch of building hours and bus schedules got corrected! Most of these are already up-to-date in version 2.4.0—we only changed some stuff behind the scenes.

# UPDATES #
• Lots of improvements under the hood!
```

## Checklist
- [x] [Release PR](https://github.com/StoDevX/AAO-React-Native/pull/1803) successfully builds against `master` (Follow along at [Travis:290118596](https://travis-ci.org/StoDevX/AAO-React-Native/builds/290118596))
- [x] GitHub release drafted (See [this draft](https://github.com/StoDevX/AAO-React-Native/releases/tag/untagged-cee156cb4510dfbce492) or just the [releases page](https://github.com/StoDevX/AAO-React-Native/releases))
- [x] Signed-off/approved
- [x] GitHub release created
- [x] Tag build passes (Follow along at [Travis:290242371](https://travis-ci.org/StoDevX/AAO-React-Native/builds/290242371))
- [x] Merge into `master`

### CODE REVIEW

**Comment by drewvolz** [comment]
> we're getting better at things

:+1: 

> we only changed the fallback data

Can we nix that, please?

> Lots of the components we depend on have been updated!

Maybe change this to the defacto "Lots of improvements under the hood"

**Comment by drewvolz** [comment]
I have a hard time using technical terms with users. That's really all I'm trying to say here. But I honestly can go either way.

**Comment by rye** [comment]
Per @drewvolz's feedback that I agree with, changed:
>we only updated the fallback data

to

>Most of these are already up-to-date in version 2.4.0—we only changed some stuff behind the scenes.

- - -

Also,
>Lots of the components we depend on have been updated!

to

>Lots of improvements under the hood!

EDIT: Also updated the wiki and the release draft.

**Review by hawkrives — APPROVED** [review]

**Comment by rye** [comment]
v2.4.1 release build can be found here: https://travis-ci.org/StoDevX/AAO-React-Native/builds/290242371

**Pull request merged**
