### PR TITLE
Update to Travis' Xcode9 images

### PR DESCRIPTION
**Pull request by hawkrives**
- [x] does it build
- [ ] does it break nightlies

### CODE REVIEW

**Comment by hawkrives** [comment]
I'm checking some of the output just to _check_ things, but @drewvolz and I have been developing with Xcode 9 for the last few weeks, and it's been working great.

**Comment by hawkrives** [comment]
### Xcode 8

```bash
$ travis logs 4138.3 | python3 scripts/analyze-gym.py -s 20
displaying logs for StoDevX/AAO-React-Native#4138.3
0m 53s: React/double-conversion [Release]
  0m 50s: Running script 'Install Third Party'
0m 36s: React/third-party [Release]
0m 11s: React/jschelpers [Release]
1m 06s: React/cxxreact [Release]
2m 22s: React/React [Release]
  0m 26s: Running script 'Include RCTJSCProfiler'
0m 36s: KSCrash-iOS/KSCrashLib [Release]
0m 14s: Bugsnag/BugsnagLib [Release]
0m 10s: BugsnagReactNative/BugsnagReactNative [Release]
0m 10s: RCTOneSignal/RCTOneSignal [Release]
0m 17s: RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge [Release]
4m 24s: AllAboutOlaf/AllAboutOlaf [Release]
  3m 47s: Running script 'Bundle React Native code and images'
```

### Xcode 9

```bash
$ travis logs 4144.3 | python3 scripts/analyze-gym.py -s 20
displaying logs for StoDevX/AAO-React-Native#4144.3
0m 42s: React/double-conversion [Release]
  0m 38s: Running script 'Install Third Party'
0m 39s: React/third-party [Release]
0m 11s: React/jschelpers [Release]
1m 07s: React/cxxreact [Release]
2m 21s: React/React [Release]
  0m 22s: Running script 'Include RCTJSCProfiler'
0m 32s: KSCrash-iOS/KSCrashLib [Release]
0m 11s: Bugsnag/BugsnagLib [Release]
0m 10s: BugsnagReactNative/BugsnagReactNative [Release]
0m 10s: RCTOneSignal/RCTOneSignal [Release]
0m 14s: RCTGoogleAnalyticsBridge/RCTGoogleAnalyticsBridge [Release]
4m 15s: AllAboutOlaf/AllAboutOlaf [Release]
  3m 37s: Running script 'Bundle React Native code and images'
```

It doesn't look like Xcode 9 improved our times much, which is pretty much what I expected.

**Comment by hawkrives** [comment]
The only way we'll know if this breaks nightlies is by merging it and seeing what happens tomorrow!

**Review by rye — APPROVED** [review]
We'll have to see what it does!

**Pull request merged**
